### ISSUE TITLE
VC: removing use of 'legacy-unknown' signerName

### ISSUE THREAD

**Issue by munnerz** [kubernetes-sigs/multi-tenancy#1002]
The Kubernetes `certificates.k8s.io` API was extended in Kubernetes 1.18 to include a new field, `spec.signerName`.

The intention of this field is to allow requesters to choose who/which 'signer' will sign the requested certificate, similar to the `spec.issuerRef` field found on cert-manager resources too.

Previously, before the existence of this field, there was no way to indicate *who* should sign a certificate, and therefore kube-controller-manager would universally sign all CertificateSigningRequest resources that are 'approved' for signing.

In order to allow different parties (e.g. cert-manager, or whatever other signing controller) to inter-operate, the `signerName` field allows developers to indicate who should sign the certificate, and therefore makes the API extensible.

For Kubernetes' own purposes, kube-controller-manager now implements a small number of signers with the `kubernetes.io/*` prefix: https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

For backwards compatibility reasons, the `kubernetes.io/legacy-unknown` signerName still exists in order to allow users who have utilised the API as a general purpose certificate signer to continue to operate. In v1 of the CSR API (due in 1.19), the `kubernetes.io/legacy-unknown` signerName will be disallowed.

---

Right now the webhook for virtual cluster requests certificates from the CSR API, relying on the `legacy-unknown` behaviour to make it work: https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go

This code also makes the (incorrect) assumption that the service account `ca.crt` (https://github.com/kubernetes-sigs/multi-tenancy/blob/167c0ea841321c1ac3743e44bb864b9511b79617/incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go#L68) will always be the root of trust for the certificates signed by this API.

In order to move forward and begin consuming the v1 API, as well as properly making use of it and avoiding the assumptions around the root of trust, virtual cluster should be adapted to no longer rely on a `signerName` within the `kubernetes.io/` namespace. Instead, there should be a signer that virtual cluster uses to request certificates (and the CA file should be provisioned either out of band or via some other component, as the current CSR API does *not* handle/touch upon trust distribution).

As a reference implementation, the cert-manager project has some experimental `signer-ca`, `signer-venafi` etc projects that implement this CSR API. These could either be directly depended upon, or otherwise copied across: https://github.com/cert-manager/signer-ca

I have also begun (quite a long time ago now) to put together a 'webhook operator' which intends to simplify this entire process for web hooks in Kubernetes. It may be worthwhile picking up this work or adapting it for our needs: https://github.com/cert-manager/webhook-operator/pull/1

**Comment by howardjohn** [comment]
Any plans for how this will be addressed?

**Comment by munnerz** [comment]
Not as of yet - the thinking would be to do one of (or a combination of):

* allow users to change which `signerName` is used for CSRs that we create (perhaps with different signerNames for different types of certificate role, to allow for finer grained, per-type 'approver' policies)
* ship a default, naive signing implementation (akin to cert-manager's 'CA' issuer)

A similar situation/set of options to what Istio's looking at doing, from what I understand!
