### ISSUE TITLE
Minikube Getting started guide does not work with the default docker driver

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/multi-tenancy#1008]
https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/virtualcluster/doc/demo.md

The getting started guide does not work with the minikube docker driver. Minikube should be explicitly started with `minikube start --driver=hyperkit`

After following the instructions with the docker driver, the virtual cluster control plane cannot be reached and will hang until timeout on this command: `kubectl get node --kubeconfig vc-1.kubeconfig`

I also notice TLS Handshake errors within the virtual cluster APIserver when using the default docker driver.

**Comment by christopherhein** [comment]
Want to add a note about not using the `docker` driver when running on macOS to the doc/demo.md?
