### ISSUE TITLE
HNC: Complete code review for sub-project graduation

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1009]
Complete a code review with approvals from at least one sig-auth technical lead as part of the graduation criteria to become a sub-project.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1687-hierarchical-namespaces-subproject/README.md#graduation-criteria

/assign @mikedanese 
/cc @rjbez17

**Comment by mikedanese** [comment]
This is done.

/close
