### ISSUE TITLE
HNC: compile the plugin for Mac

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1029]
Todo: add the appropriate flags to the makefile, and then update `cloudbuild.yaml` to rebuild the plugin for multiple OSes.

**Comment by tcnksm** [comment]
Since we want to have this, let me try to contribute this!

**Comment by adrianludwin** [comment]
This is now fixed on the trunk. I'll backport to 0.5.2.

**Comment by adrianludwin** [comment]
Fixed by #1049 
/close

**Comment by adrianludwin** [comment]
/reopen
/assign @tcnksm 

Hi Taichi, can you please verify that [HNC v0.5.2 RC1](https://github.com/kubernetes-sigs/multi-tenancy/releases/tag/hnc-v0.5.2-rc1) works for you - both the YAML files but also the Darwin plugin? I don't have any ability to test on MacOS. Thanks!

**Comment by tcnksm** [comment]
> Hi Taichi, can you please verify that HNC v0.5.2 RC1 works for you - both the YAML files but also the Darwin plugin? I don't have any ability to test on MacOS. Thanks!

Ok. Let me confirm those.

## Darwin plugin

I've executed the following command by following the release note instruction.

```bash
$ HNC_VERSION=v0.5.2-rc1
$ HNC_PLATFORM=darwin_amd64
$ $ curl -L https://github.com/kubernetes-sigs/multi-tenancy/releases/download/hnc-{HNC_VERSION}/kubectl-hns_${HNC_PLATFORM} -o ./kubectl-hns
$ chmod +x ./kubectl-hns
```

And run the following command to confirm help message is shown.

```bash
$ kubectl hns
```

## Generated YAML

I've applied to our lab GKE cluster (1.15) by following the release note instruction.

```
$ HNC_VERSION=v0.5.2-rc1
$ kubectl apply -f https://github.com/kubernetes-sigs/multi-tenancy/releases/download/hnc-${HNC_VERSION}/hnc-manager.yaml
```

And run the following commands to confirm `timeoutSeconds` configuration is properly configured. 

```bash
$ kubectl get validatingwebhookconfiguration hnc-validating-webhook-configuration -o yaml
```

**Comment by adrianludwin** [comment]
Great, thanks! I'll call that "confirmed" and we'll release 0.5.2 in a day or two (there's one more change I'd like to get in).

/close
