### ISSUE TITLE
HNC: Use Krew (attempt two)

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1030]
/assign @adrianludwin

**Comment by evalsocket** [comment]
@adrianludwin I have an idea about krew. Can this assign to me?

**Comment by adrianludwin** [comment]
Thanks for the offer! I'm getting pretty close a solution though - it's here if you want to check it out: https://github.com/adrianludwin/multi-tenancy/commit/eaf823382ac24b836072182032ed29ba14a41b16

As you can see, there's quite a lot of stuff you need to know about our build process to get this right. Hopefully we're done soon. Right now I'm just getting a checksum error I can't track down but I've asked the Krew maintainers for help.

If you're looking for a place to help out, we have a list of bugs that are looking for help [here](https://github.com/kubernetes-sigs/multi-tenancy/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+HNC) - please chime in on any bugs you'd like to help out on. Thanks!
