### ISSUE TITLE
HNC: test function TearDownHNC can fail silently

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1041]
/cc @GinnyJI 
/cc @yiqigao217 

Ginny and I were looking at a test where it _seems_ like the command to delete the subns CRD failed (as evidenced by the fact that there were still subnses afterwards) but because we use `TryRunQuietly` there was no evidence of this.

We should have some better function that can delete objects if they exist, but if they _can't_ delete an object, return an error.

**Comment by mayankshah1607** [comment]
Hi @adrianludwin , I'd like to give this issue a try. :) 
I just looked into the code, and I see that we have an alternate function `TryRun` that logs the errors when the command returns an error. Is there any reason why we may not be able to use this?
Thanks

**Comment by adrianludwin** [comment]
Hey Mayank, sorry I've been on vacation this last week. I'll reply when I'm
back after Labour Day (i.e. early next week). Thanks!

**Comment by mayankshah1607** [comment]
No problem. Have a great vacation! 🙂

**Comment by adrianludwin** [comment]
Hey let me know if you need any advice on this but any PRs would be welcome!

**Comment by mayankshah1607** [comment]
Hi, @adrianludwin . Thanks!
I was just trying to wrap my head around this issue, and tried to look into the code. The issue mainly talks about how the tests did not leave any evidence when the CRD deletion failed (due to `TryRunQuietly`). 
I see that we have an alternate function called `TryRun` that will log these failures. Would it help if we used `TryRun` instead?

**Comment by adrianludwin** [comment]
I believe the problem is that we _expect_ some of the commands in the cleanup to fail - e.g., if we try to delete a namespace that we never created. In those cases, I think we do want `TryRunQuietly` to avoid printing too much logspam. However, if the namespace _does_ exist, it should be deleted successfully.

I think you're also looking at another bug that has a better way to clean up the namespaces without relying on exact names. If so, running that command with `TryRun`, and not `TryRunQuietly`, seems like the right thing to do.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/26

/close
