### ISSUE TITLE
HNC: CleanupNamespaces shouldn't require an explicit list of namespaces

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1043]
We should have dedicated `CreateNamespace` and `CreateSubnamespace` functions that add some kind of label (e.g. `hnc.x-k8s.io/testNamespace: true`) to all namespaces, so we can just search by label in `CleanupNamespaces` and not require an explicit list.

/good-first-issue
/cc @GinnyJI 
/cc @yiqigao217

**Comment by mayankshah1607** [comment]
@adrianchung Can I take up this one if no one is working on it already? Thanks!
/assign

**Comment by adrianludwin** [comment]
Go for it!

**Comment by venkatnsrinivasan** [comment]
Hi
I attempted to try and work on this issue and opened a PR here 
https://github.com/kubernetes-sigs/multi-tenancy/pull/1283 . Any suggestions and guidance are welcome . hopefully the PR is on the right path

Thanks

**Comment by adrianludwin** [comment]
This was fixed by #1283 - thanks @venkatnsrinivasan !

/close
