### ISSUE TITLE
HNC: don't propagate objects with initializers or finalizers

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#106]
We wipe away the initializers and finalizers on any propagated objects. Instead, we should probably refuse to propagate any object that has an initializer or finalizer. See #201 for a continuation of this feature.

**Comment by entro-pi** [comment]
I'd like to take this one on!

/assign @entro-pi

**Comment by entro-pi** [comment]
The propagation as well as initialization is done through the hierarchy and object controllers as far as I can tell. This will take a few days to digest exactly how these two behave. If anyone has any pointers to different sections of code to study, please let me know!

**Comment by adrianludwin** [comment]
This should be done entirely through the object controller; the hierarchy controller just sets up the hierarchies, but the object controller actually does the propagation.

You can ask @yiqigao217 for help (that's her Slack handle too) since she's been working on the object controller.

**Comment by entro-pi** [comment]
Cool! Thanks!

**Comment by adrianludwin** [comment]
@entro-pi told me they aren't able to work on this for now, so unassigning.

/unassign
