### ISSUE TITLE
HNC: Demo doesn't work as expected

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#1067]
In [HNC demo](https://docs.google.com/document/d/1tKQgtMSf0wfT3NOGQx9ExUQ-B8UkkdVZB6m4o3Zqn64), under "Hierarchical network policy" part, In the 6th block where it says `Now we’ll see that we can no longer access service-2 from client a client in service-1`, it appears that you can still access `service-2` from a client in `client-1` after following all the pre-setups. As a result, the e2e test also fails on this part.

**Comment by GinnyJI** [comment]
Terminal output:
```$ kubectl get netpol --all-namespaces | grep deny
acme-org    deny-from-other-namespaces   <none>         7m26s
service-1   deny-from-other-namespaces   <none>         7m26s
service-2   deny-from-other-namespaces   <none>         7m26s
team-a      deny-from-other-namespaces   <none>         7m26s
team-b      deny-from-other-namespaces   <none>         7m26s
$ kubectl run client -n service-1 -it --image=alpine --restart=Never  --rm -- sh
If you don't see a command prompt, try pressing enter.
/ # wget -qO- --timeout 2 http://s2.service-2
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by yiqigao217** [comment]
Hmm did you enable network policy in your cluster? Or I remember there was no way to enable networkPolicy on Kind? I just tried it late last week on a GKE cluster with networkPolicy enabled and it worked.

**Comment by GinnyJI** [comment]
Sry false alarm, the test failed because network policy was not enabled. [Made changes](https://github.com/kubernetes-sigs/multi-tenancy/pull/1068#pullrequestreview-479871794) to reminder user who meet the same issue again.
