### ISSUE TITLE
HNC: kubectl-hnc should not allow duplicate requiredChildren

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#108]
See comment in `pkg/kubectl/sub.go`.

/good-first-issue

**Comment by vjdhama** [comment]
@adrianludwin I would like to take this up. I am new to multi-tenancy WG, so would need some general direction.

Code you are referring to, is this, right?

https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/pkg/kubectl/sub.go#L32

**Comment by adrianludwin** [comment]
Thanks! Yup, that's the right line, exactly. Feel free to take this issue
and start working on it.

I've got a better README on the way:
https://github.com/kubernetes-sigs/multi-tenancy/pull/121. Please check
that out and let me know (ideally on Slack) if you're having any issues.
Thanks!

**Comment by vjdhama** [comment]
@adrianludwin Thanks for the info. I'll bug you on slack if I run into issues. Cheers.

**Comment by adrianludwin** [comment]
Actually, can you work on #131 instead, which will include this issue?

Also, are you a member of `kubernetes-sigs`? If so, you should be able to assign this to yourself.

**Comment by vjdhama** [comment]
Cool. I will start with that.

**Comment by adrianludwin** [comment]
Fixed as a part of #152
