### ISSUE TITLE
HNC: configure Prow for presubmit testing

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#110]
/assign @danielSbastos

**Comment by adrianludwin** [comment]
Thanks @danielSbastos for working on this!

**Comment by danielSbastos** [comment]
> Thanks @danielSbastos for working on this!

![Alt Text](https://media.giphy.com/media/Ep94i7XsV92ow/giphy.gif)

**Comment by adrianludwin** [comment]
This _may_ be fixed at https://github.com/kubernetes/test-infra/pull/14660?

**Comment by adrianludwin** [comment]
This was fixed by https://github.com/kubernetes/test-infra/pull/14921 and https://github.com/kubernetes/test-infra/pull/14891.
