### ISSUE TITLE
[vc]: /healthz endpoint for vc-syncer and vc-manager

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/multi-tenancy#1112]
We've noticed that the current vc-syncer exposes :8080 for doing liveness with tcp endpoints to follow Kubernetes standards can we change this to expose a `/healthz` and return "ok" when successful?

Also it appears that the `vc-manager` doesn't have any health or liveness checks would it make sense to also expose the same endpoint for `vc-manager`?

/cc @miamipanther

**Comment by Fei-Guo** [comment]
Sure, we can add health check for both controllers. I just don't quite see how the health check for controllers will help in any use case. If the controller crashed, the Pod status will reflect the failure.  The controllers also may not need readiness gate to coordinate with other systems.

**Comment by miamipanther** [comment]
If we have health check for important component, we can set up external probe to monitor and alert if those components go unhealthy

**Comment by Fei-Guo** [comment]
For controllers, monitoring Pod status and monitoring healthz seems to be equivalent in term of debugging/alarming purposes. Of course, providing a standard interface for monitoring is a pro. I am fine with adding those. I am Just curious if there are other use cases.

**Comment by miamipanther** [comment]
Thanks @Fei-Guo , we will add the standard interface

**Comment by miamipanther** [comment]
https://github.com/kubernetes-sigs/multi-tenancy/pull/1147
