### ISSUE TITLE
[MTB] Add Kyverno Policy - Require a PodDisruptionBudget

### ISSUE THREAD

**Issue by realshuting** [kubernetes-sigs/multi-tenancy#1116]
https://thenewstack.io/kubernetes-use-poddisruptionbudgets-for-application-maintenance-and-upgrades/

**Comment by evalsocket** [comment]
@JimBugwadia Can you provide me some information regarding the issue ?

**Comment by JimBugwadia** [comment]
PDBs are a good best practice, but not required for multi-tenancy. Will open a separate issue for a Kyverno best practice policy.
