### ISSUE TITLE
[VC] proposal: kubectl vc command line tool

### ISSUE THREAD

**Issue by zhuangqh** [kubernetes-sigs/multi-tenancy#1118]
## Motivation

super cluster admin managed all of the virtual clusters. They usually switch between different vc. First find the kubeconfig, then switch to this cluster. We need a command line tool to manage multi clusters.

### kubectl vc create xxx

create a virtual cluster and waiting it to be running. export kubeconfig to specific path.

### kubectl vc delete xxx

delete a virtual cluster 

### kubectl vc config -n $vc_cr_ns $vc_cr_name

switch to a vc kubeconfig 

### kubectl vc -n $vc_cr_ns $vc_cr_name xxx

switch to a vc context and do normal kubectl command

**Comment by zhuangqh** [comment]
@Fei-Guo @charleszheng44

**Comment by Fei-Guo** [comment]
This is going to be very useful!

A few comments:

`kubectl vc config -n $vc_cr_ns $vc_cr_name` will be optional if we have `kubectl vc -n $vc_cr_ns $vc_cr_name xxx` been available.

We can combine "-n $vc_cr_ns $vc_cr_name" to a single "vcfullname" as input so the cmd can be as simple as

`Kubectl vc admin1/vc-sample1 get pod -A`

**Comment by charleszheng44** [comment]
+1 for the vc subcommand :+1:

**Comment by salaxander** [comment]
This was something I have been thinking about too! I had originally considered extending `vcctl`, but I like the idea of a `kubectl` plugin!
