### ISSUE TITLE
HNC: Add object webhook rules for updating a source object

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1120]
Another corner case of #1076 

If a user removes the finalizers of a source object, it may cause source object overwriting in descendants too. Because source objects with finalizers cannot be propagated, thus there was no risk of overwriting source objects in descendants before the change.

With this new corner case, we will need to revisit the object and hierarchy webhooks on not just the naming conflict but also check if the ancestor object with naming conflict has finalizers too. If it does, we should allow it since there's no potential source object overwriting.

**Comment by yiqigao217** [comment]
/cc @adrianludwin 
/assign @GinnyJI 

There's no rush for this corner case.

**Comment by yiqigao217** [comment]
/remove-lifecycle stale

This can remain in the backlog since is a rare corner case.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/27

/close
