### ISSUE TITLE
HNC: exceptions feature

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#1123]
This issue is to track the implementation of exceptions, the design doc can be found at https://docs.google.com/document/d/17J8icBEDvLLoPT4kQ4ArZcCerRweDY-TpJ48DJKpHJ0

**Comment by adrianludwin** [comment]
This isn't _required_ for HNC v0.6 to moving to v0.7. However much we can get done in v0.6 is what we'll release.

**Comment by adrianludwin** [comment]
I think we're done here - nice work!

/close
