### ISSUE TITLE
HNC: Update `kubectl hns config set-type` to allow force updating

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1133]
Part of #1102, #1076 

Changing the sync mode to `Propagate` may cause source object overwriting. The HNCConfig webhook will deny such requests, but we will allow user to fix it quickly with a force update.

We can achieve it in either of the two ways (depending on which is easier to implement):
1. Add a confirmation prompt that users can say `yes` to proceed (as suggested in https://github.com/kubernetes-sigs/multi-tenancy/issues/1102#issuecomment-692086619)
2. Add a `--force` flag that users can use directly.

For either approach, we will first list the conflicts, show the warning and a link to the [doc](http://bit.ly/hnc-propagation-conflict).  Then we will tell user how to fix, e.g. rename objects and retry, answer `yes` to the confirmation prompt, or run `kubectl hns config set-type --force`.

**Comment by adrianludwin** [comment]
@GinnyJI I believe this is done, correct?

**Comment by adrianludwin** [comment]
Did we link to the doc as we said we would?

**Comment by yiqigao217** [comment]
fixed by #1169 .
Doc link -  http://bit.ly/hnc-propagation-conflict
