### ISSUE TITLE
HNC: support `kubectl explain` and `kubectl describe`

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1153]
https://www.youtube.com/watch?v=zAtaJ0x-ZwY&feature=youtu.be

**Edit Oct 12**:
* Explain: https://youtu.be/zAtaJ0x-ZwY?t=2823

**Comment by frbimo** [comment]
Hi @adrianludwin , i may need your guidance. i tried to reproduce result on youtube video, so i deployed self-built hnc on branch 0.5.3. 
executing command `kubectl explain  hierarchyconfigurations.hnc.x-k8s.io` & `kubectl explain hierarchyconfigurations`, both returns 
```
KIND:     HierarchyConfiguration
VERSION:  hnc.x-k8s.io/v1alpha1

DESCRIPTION:
     <empty>
```

on branch master, `kubectl explain  hierarchyconfigurations.hnc.x-k8s.io` returns
```
error: field "hnc" does not exist
```
while  `kubectl explain hierarchyconfigurations` returns 
```
KIND:     HierarchyConfiguration
VERSION:  hnc.x-k8s.io/v1alpha2

DESCRIPTION:
     Hierarchy is the Schema for the hierarchies API

FIELDS:
   apiVersion   <string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind <string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata     <Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

   spec <Object>
     HierarchySpec defines the desired state of Hierarchy

   status       <Object>
     HierarchyStatus defines the observed state of Hierarchy
```
is this behavior expected?

**Comment by adrianludwin** [comment]
I've never run either `explain` or `describe` before so I'm not sure what _should_ happen, but it looks like `explain` needs a bit more documentation to make it work. What's a bit weird is that all our fields _are_ documented (e.g. [here](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml#L41), although the actual source of this text is [here](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/api/v1alpha2/hierarchy_types.go#L121)) but those descriptions aren't showing up in `explain`. If you could figure out what the K8s `explain` feature is supposed to do and see if we need to do something different to get our documentation to show up, that might be useful!

What happens if you ask for `describe`?

**Comment by frbimo** [comment]
`kubectl describe crd hierarchyconfigurations.hnc.x-k8s.io` will shows crd details as similar in [here](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml#L41) (its kinda long to post)

as `kubectl explain` [will publish OpenAPI schema documentation](https://github.com/kubernetes/kubernetes/issues/82407#issuecomment-528919183)

> ... but those descriptions aren't showing up in explain.

i assume the description you were mentioned is Object type. This can be accessed using object notation. So from example above, if we want to emphasis description of field `spec`, need to use `kubectl explain hierarchyconfigurations.spec` that will shows 
```
KIND:     HierarchyConfiguration
VERSION:  hnc.x-k8s.io/v1alpha2

RESOURCE: spec <Object>

DESCRIPTION:
     HierarchySpec defines the desired state of Hierarchy

FIELDS:
   allowCascadingDeletion       <boolean>
     AllowCascadingDeletion indicates if the subnamespaces of this namespace are
     allowed to cascading delete.

   parent       <string>
     Parent indicates the parent of this namespace, if any.
```

thats why we can't use crd full name hierarchyconfigurations.hnc.x-k8s.io because there is no object `hnc` on the description.

**Comment by frbimo** [comment]
FYI, i tested it using:
go 1.14
controller-gen 0.2.8
kubernetes 1.18

as behavior i mentioned above, overall `kubectl explain` and `kubectl describe` perform normally as they should.
Please tell me if i miss something.

**Comment by adrianludwin** [comment]
I reviewed the video (at high speed, skipping a lot) and I couldn't find him explicitly talking about `kubectl describe`. I think I just had the idea that there's some way of including more data about an object (not necessarily the CRD itself, but any one CR) when the user says, say, `kubectl describe subns foo`, but I don't know how extensible `describe` is.

@frbimo , it would be great if you could look into how `k describe` can be extended and let us know if you think there's anything we _should_ be adding to HNC to make it work better. Thanks!
