### ISSUE TITLE
HNC: exceptions error handling

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#1165]
We should surface the potential errors in exceptions. Eg: when the annotation could not be parsed to selector.

**Comment by adrianludwin** [comment]
We'll try to get as much of this done in v0.6 as possible but it's not blocking.

**Comment by adrianludwin** [comment]
Is this finished?

**Comment by yiqigao217** [comment]
Are we surfacing these error as events? Seemed the [plan](https://docs.google.com/document/d/1WyPkx4_eRsH5rgAAF7stLUZmW_rq7qURH5CmpVZRIsk/edit#heading=h.jia3ritthiby) was surfacing them as events.

**Comment by yiqigao217** [comment]
@GinnyJI  here's an example of generating events in HNC. You may just replace the error with generating events.
