### ISSUE TITLE
HNC either fails or takes very long time to remove subnamespace in RBAC-enabled K8S cluster

### ISSUE THREAD

**Issue by droopy4096** [kubernetes-sigs/multi-tenancy#1180]
Currently what we are observing is a situation where two different scenarios produce significantly different results.

# Subnamespace flow

```
 282 11:43  ~ $ k hns create -n parent1 foo-test3
Successfully created "foo-test3" subnamespace anchor in "parent1" namespace
> 282 11:46  ~ $ k delete subns --namespace parent1 foo-test3
subnamespaceanchor.hnc.x-k8s.io "foo-test3" deleted
> 282 13:04  ~ $ 
```
Note 1h+ delay

what we've discovered that if we execute 
```
k annotate namespace foo-test3  hnc.x-k8s.io/subnamespaceOf-
```
while `delete` process "hangs" - it unlocks the process and it completes as expected. Also to note - sometimes it fails with 
```
$ k delete namespace foo-test3
Error from server (Forbidden): admission webhook "namespaces.hnc.x-k8s.io" denied the request: The namespace foo-test3 is a subnamespace. Please delete the anchor from the parent namespace parent1 to delete the subnamespace.
```
and I have no exact flow to reproduce it, but once I get it I can post it here.

# Full Namespace flow

```
k create namespace foo-test3
k hns set foo-test3 --parent parent1
k delete namespace foo-test3
```
this works as expected but removes our ability to allow users to create *subnamespace* and inherit all the permissions from the parent1. 

Environment details:
K8S is Azure Kubernetes with AAD-backed RBAC
```$ k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"afea77eefe3272c0f53c4552183ecb16c091db41", GitTreeState:"clean", BuildDate:"2020-09-17T06:32:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
latest HNS plugin on client side

**Comment by adrianludwin** [comment]
Are you using HNC v0.5.2? If so this is probably #1130 which was fixed in HNC v0.5.3.

Otherwise, can you let me know what was in `parent1` and what's the contents of your cluster-wide config (`kubectl hns config describe`)? Thanks!

**Comment by droopy4096** [comment]
great. it worked.

**Comment by adrianludwin** [comment]
Glad to hear! Let us know if you run into any other issues.
