### ISSUE TITLE
HNC: Configure the list of HNC-controlled objects at the cluster level

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#120]
Issue #91 hardcodes the initial list of GVKs controlled by HNC. We should make this configurable.

**Comment by adrianludwin** [comment]
/unassign
/remove-lifecycle rotten

@sophieliu15 is working on this now

**Comment by sophieliu15** [comment]
[Duplicate] Please see #411 for progress.

Close this issue for now.

/close
