### ISSUE TITLE
HNC: validate `hnc.x-k8s.io` annotations

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#1206]
We should check for any unwanted `hnc.x-k8s.io` fields. For example, we are looking for `propagate.hnc.x-k8s.io/select` but NOT `propagate.hnc.x-k8s.io/selector`. We should prevent the user from setting the latter one.

**Comment by adrianludwin** [comment]
Is this finished?

**Comment by GinnyJI** [comment]
No this hasn't been implemented yet
