### ISSUE TITLE
HNC: metav1.StatusReasonInvalid produce double colons when formatting error message

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#1218]
metav1.StatusReasonInvalid produces `The request is invalid: : ` which has repeated colons

**Comment by kailinwei** [comment]
I would like to work on this, would you mind assign me in?

**Comment by adrianludwin** [comment]
I probably can't formally assign it to you (you need to be a member of
kubernetes-sigs - if you are, please assign it to yourself) but feel free
to go ahead and work on it!

**Comment by kailinwei** [comment]
Hello Adrian,
  Thank you. This is my first time using github, so glad to get my first
feedback.
Have a nice day!
Kailin

**Comment by frbimo** [comment]
@adrianludwin is `metav1.StatusReasonInvalid` will be limited to invalid tree selector?

**Comment by frbimo** [comment]
This issue caused by string format on https://github.com/kubernetes/kubectl/blob/86e211da3df4f82b59a9ce5ff795050d211ac074/pkg/cmd/util/helpers.go#L198 that concatenate field `Field` on `metav1.StatusCause` as part of it.

so, on https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/internal/validators/hierarchy.go#L551-L555 without filling `Field` it will printout empty string in between double colons.

**Comment by adrianludwin** [comment]
/cc @GinnyJI what can cause this problem ("will metav1.StatusReasonInvalid be limited to invalid tree selector?")?

@frbimo we don't see this double colon problem for all of our messages, and I don't _think_ we've _ever_ set the fields before. Can you tell why this is only happening with this one error message?

**Comment by frbimo** [comment]
not the error message instead the error reason. 
AFAIK kubectl handles error differently particularly if  reason is `metav1.StatusReasonInvalid`. 
https://github.com/kubernetes/kubectl/blob/86e211da3df4f82b59a9ce5ff795050d211ac074/pkg/cmd/util/helpers.go#L145-L160

**Comment by frbimo** [comment]
```
bee@pop-os:~$ k annotate role test -n a "propagate.hnc.x-k8s.io/treeSelect"="12345678901234567890123456789012345678901234567890123456789012345678" --overwrite
The request is invalid: : Invalid HNC "propagate.hnc.x-k8s.io/treeSelect" value: "12345678901234567890123456789012345678901234567890123456789012345678" is not a valid namespace name: must be no more than 63 characters
bee@pop-os:~$ k annotate role test -n a "propagate.hnc.x-k8s.io/select"="12345678901234567890123456789012345678901234567890123456789012345678" --overwrite
The request is invalid: : Invalid Kubernetes labelSelector: while parsing "propagate.hnc.x-k8s.io/select": couldn't parse the selector string "12345678901234567890123456789012345678901234567890123456789012345678": unable to parse requirement: invalid label key "12345678901234567890123456789012345678901234567890123456789012345678": name part must be no more than 63 characters
```

as you can see, i have changed  reason to `metav1.StatusReasonInvalid` and the issue is reproducible for different messages

**Comment by adrianludwin** [comment]
What did you change between those two messages?

What data do you think we're _supposed_ to be adding to the error details
that we're not?

**Comment by frbimo** [comment]
> What did you change between those two messages? What data do you think we're _supposed_ to be adding to the error details that we're not?

```
...
		if err := validateSelectorChange(inst, oldInst); err != nil {
			msg := fmt.Sprintf("Invalid Kubernetes labelSelector: %s", err)
			return deny(metav1.StatusReasonBadRequest, msg)
		}
		if err := validateTreeSelectorChange(inst, oldInst); err != nil {
			msg := fmt.Sprintf("Invalid HNC %q value: %s", api.AnnotationTreeSelector, err)
			return deny(metav1.StatusReasonBadRequest, msg)
		}
...
```
modified to 

```
...
		if err := validateSelectorChange(inst, oldInst); err != nil {
			msg := fmt.Sprintf("Invalid Kubernetes labelSelector: %s", err)
			return deny(metav1.StatusReasonInvalid, msg)
		}
		if err := validateTreeSelectorChange(inst, oldInst); err != nil {
			msg := fmt.Sprintf("Invalid HNC %q value: %s", api.AnnotationTreeSelector, err)
			return deny(metav1.StatusReasonInvalid, msg)
		}
...
```

**Comment by adrianludwin** [comment]
Oh, so what you're saying is: _before_ changed `StatusReasonBadRequest` to `StatusReasonInvalid`, the error message _didn't_ have the double colons. _After_ you made that change, it did. Correct?

If so, what do you think the right fix is? Should we not use `StatusReasonInvalid`? Or should we pass some additional information back to kubectl so that something useful is displayed before the "extra" colon?

**Comment by frbimo** [comment]
> Oh, so what you're saying is: _before_ changed `StatusReasonBadRequest` to `StatusReasonInvalid`, the error message _didn't_ have the double colons. _After_ you made that change, it did. Correct?
> 

correct
> If so, what do you think the right fix is? Should we not use `StatusReasonInvalid`? Or should we pass some additional information back to kubectl so that something useful is displayed before the "extra" colon?

The field `Field` should have value that indicates location of the error e.g `.items[0].metadata.annotations`
so the final error message would be 
```
The request is invalid: .items[0].metadata.annotations : Invalid Kubernetes labelSelector: while parsing "propagate.hnc.x-k8s.io/select": couldn't parse the selector string "12345678901234567890123456789012345678901234567890123456789012345678": unable to parse requirement: invalid label key "12345678901234567890123456789012345678901234567890123456789012345678": name part must be no more than 63 characters
```

**Comment by frbimo** [comment]
But personally, i dont think stacking multiple errors like above would makes us easier to know what happened.
If you want to stay with `StatusReasonInvalid`, i think we can remove the additional string and make it as
```
The request is invalid: .items[0].metadata.annotations : couldn't parse the selector string "12345678901234567...
```
But it means,  `StatusReasonInvalid` would be limited to error that related to annotation.

Another way is to change it into different status reason if possible

**Comment by adrianludwin** [comment]
We definitely shouldn't hardcode the "annotations" field into the
StatusReasonInvalid. Maybe we can add a `denyInvalid(field, msg)` function
that, under the hood, calls `deny` but then adds `field` before returning
the error object?

**Comment by frbimo** [comment]
> We definitely shouldn't hardcode the "annotations" field into the StatusReasonInvalid. Maybe we can add a `denyInvalid(field, msg)` function that, under the hood, calls `deny` but then adds `field` before returning the error object?

agree we shouldn't hardcode. 
if `denyInvalid(field, msg)` calls `deny(reason, msg)` how can it adds the field without changing `deny` input args?

**Comment by adrianludwin** [comment]
[deny](https://github.com/kubernetes-sigs/multi-tenancy/blob/c26a4ea74417ce1764458e96142483a2aef4e128/incubator/hnc/internal/validators/hierarchy.go#L519) returns `admission.Response`, which is just a struct. You can modify any fields in that struct before returning it.

**Comment by frbimo** [comment]
> [deny](https://github.com/kubernetes-sigs/multi-tenancy/blob/c26a4ea74417ce1764458e96142483a2aef4e128/incubator/hnc/internal/validators/hierarchy.go#L519) returns `admission.Response`, which is just a struct. You can modify any fields in that struct before returning it.

should i open PR for this?

**Comment by adrianludwin** [comment]
Please go ahead, and thank you!
