### ISSUE TITLE
HNC: detect namespace deletion without a controller

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1241]
#1236 checks whether a namespace is being deleted in the reconciler, then uses that data in the object validator. Ideally, the object validator would just do the check itself, but it doesn't have a client. I'm sure there's a way to do this which would allow us to get rid of this coupling.

/good-first-issue

**Comment by tsunny** [comment]
@adrianludwin - I would like to contribute to this issue. Could you please assign this to me?

Thanks,
Sunny

**Comment by adrianludwin** [comment]
Hi Sunny, are you a member of kubernetes-sigs? If not, I can't formally
assign it to you but either way, please feel free to go ahead and start
working on it!

**Comment by frbimo** [comment]
@adrianludwin can i take over this?

**Comment by tsunny** [comment]
@frbimo - Please take over. Sorry, I have been busy with other stuff.

**Comment by adrianludwin** [comment]
Sorry I missed this, yes please go ahead!
