### ISSUE TITLE
[VC] The syncer RBAC settings for PriorityClass and Ingress are missing

### ISSUE THREAD

**Issue by Fei-Guo** [kubernetes-sigs/multi-tenancy#1261]
We should add them into all_in_one.yaml at least for now.

**Comment by christopherhein** [comment]
Do we want them included by default since they default "off" in the controller?

**Comment by Fei-Guo** [comment]
> Do we want them included by default since they default "off" in the controller?

Either we add them by default, or we add instructions somewhere otherwise people may get stuck when they enable the new resources.
