### ISSUE TITLE
HNC:E2E tests failing 

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kubernetes-sigs/multi-tenancy#1269]
I checked out the latest master branch for HNC and tried running the e2e tests. There seem to a lot of failures with the messages

[1605319933] Running:  [kubectl delete ns recover-test-a]
Output (failed):  Error: exit status 1
Output: Error from server (Forbidden): admission webhook "namespaces.hnc.x-k8s.io" denied the request: Please set allowCascadingDeletion in the parent namespace.

If i switch to the release branch hnc-v0.6  they all seem to pass. It seems this is related to this recent commit - https://github.com/kubernetes-sigs/multi-tenancy/commit/d2914ca100499ccc7590ac6c6bc81dc299e1a55d 

Any suggestions to get around this or any pointers of what needs to fixed (if any) in the tests.?
I was trying to pickup one of the "good first issue" issues to work on where I ran into this error.

**Comment by adrianludwin** [comment]
Thanks for the report! We're trying to get the e2e tests running as
postsubmits to prevent exactly this kind of problem.

**Comment by venkatnsrinivasan** [comment]
Thanks. I got around this  'fixing' the e2e tests temporarily by adding 
		TryRunQuietly("kubectl hns set", ns, "--allowCascadingDeletion")
to "CleanupNamespaces" 
3 tests still fail for issue #716 which i am not sure are applicable anymore. 
If you think this is the right approach and want me to open a PR , do let me know.

Thanks

**Comment by GinnyJI** [comment]
Hi, thanks for the update! We are looking at this issue now, and it seems like we need more investigation.

I am able to reproduce this issue, and have got three failed tests
```
Summarizing 3 Failures:

[Fail] Issues [It] Should not delete a parent of a subnamespace if allowCascadingDeletion is not set -issue #716 
/usr/local/google/home/ginnyji/multi-tenancy/incubator/hnc/test/e2e/issues_test.go:184

[Fail] Quickstart [It] Should test basic functionalities in quickstart 
/usr/local/google/home/ginnyji/multi-tenancy/incubator/hnc/test/e2e/quickstart_test.go:52

[Fail] Quickstart [It] Should create and delete subnamespaces 
/usr/local/google/home/ginnyji/multi-tenancy/incubator/hnc/test/e2e/quickstart_test.go:217

Ran 23 of 33 Specs in 592.428 seconds
FAIL! -- 20 Passed | 3 Failed | 0 Pending | 10 Skipped
```

And if I run these test commands by hand with a freshly deployed HNC, all of them passes. However, if I manually test them right after running e2e tests, they would fail. The validating webhook does not check if the deletion is illegal or not.

@adrianludwin , any thoughts on why HNC gets into a bad state while running e2e tests?

**Comment by venkatnsrinivasan** [comment]
Thanks for the update. It is interesting . I have 3 tests failed too after my patch but those are different ones. I did run with the HNC_REPAIR path set.

Summarizing 3 Failures:

[Fail] Namespace [It] should have 'ParentMissing' condition on orphaned namespace 
/Users/venkat/development/projects/kubernetes-sigs/multi-tenancy/incubator/hnc/test/e2e/namespace_test.go:43

[Fail] Issues [It] Should have ParentMissing condition when parent namespace is deleted - issue #716 
/Users/venkat/development/projects/kubernetes-sigs/multi-tenancy/incubator/hnc/test/e2e/issues_test.go:160

[Fail] Issues [It] Should delete namespace with ParentMissing condition - issue #716 
/Users/venkat/development/projects/kubernetes-sigs/multi-tenancy/incubator/hnc/test/e2e/issues_test.go:170

Ran 32 of 33 Specs in 1138.324 seconds
FAIL! -- 29 Passed | 3 Failed | 0 Pending | 1 Skipped
