### ISSUE TITLE
uninstall multi-tenancy fail

### ISSUE THREAD

**Issue by JaneLiuL** [kubernetes-sigs/multi-tenancy#1276]
I just delete multi-tenancy namespace: `kubectl delete ns hnc-system`
Then I find my cluster something wrong now, allows tell me "service "hnc-webhook-service" not found" and something related.

Even now I try to use ` kubectl apply -f https://github.com/kubernetes-sigs/multi-tenancy/releases/download/hnc-v0.5.1/hnc-manager.yaml`  to install, still said 
"""
failed calling webhook "namespaces.hnc.x-k8s.io": Post https://hnc-webhook-service.hnc-system.svc:443/validate-v1-namespace?timeout=30s: service "hnc-webhook-service" not found
"""

**Comment by JaneLiuL** [comment]
I try to delete the webhook and fix the issue right now.
`kubectl delete validatingwebhookconfiguration.admissionregistration.k8s.io hnc-validating-webhook-configuration`

**Comment by adrianludwin** [comment]
Hi Jane, please let me know if there's anything we can do to help!
