### ISSUE TITLE
VirtualCluster demo instructions

### ISSUE THREAD

**Issue by irmishappy** [kubernetes-sigs/multi-tenancy#1280]
Following demo instructions, failing to launch etcd-0.
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15"...
Steps used:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/multi-tenancy/master/incubator/virtualcluster/config/sampleswithspec/tenancy.x-k8s.io_clusterversions.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/multi-tenancy/master/incubator/virtualcluster/config/crds/tenancy.x-k8s.io_virtualclusters.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/multi-tenancy/master/incubator/virtualcluster/config/setup/all_in_one.yaml
kubectl get all -n vc-manager
#wait till get to running state
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/multi-tenancy/master/incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
kubectl vc create -f https://raw.githubusercontent.com/kubernetes-sigs/multi-tenancy/master/incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_nodeport.yaml -o vc-1.kubeconfig
```
Output from last command: cannot find sts/etcd in ns default-952ef2-vc-sample-1: default-952ef2-vc-sample-1/etcd is not ready in 120 seconds

And here some logs from failing etcd pod:
2020-11-20 11:14:36.618875 I | embed: advertise client URLs = https://etcd-0.etcd:2379
{"level":"warn","ts":1605870906.6717532,"caller":"netutil/netutil.go:121","msg":"failed to resolve URL Host","url":"https://etcd-0.etcd:2380","host":"etcd-0.etcd:2380","retry-interval":1,"error":"i/o timeout"}
{"level":"warn","ts":1605870906.6720304,"caller":"netutil/netutil.go:131","msg":"failed to resolve URL Host; returning","url":"https://etcd-0.etcd:2380","host":"etcd-0.etcd:2380","retry-interval":1,"error":"i/o timeout"}
2020-11-20 11:15:06.682505 C | etcdmain: failed to resolve https://etcd-0.etcd:2380 to match --initial-cluster=etcd-0=https://etcd-0.etcd:2380 (failed to resolve "https://etcd-0.etcd:2380" (i/o timeout))

Any hint where to dig?

**Comment by irmishappy** [comment]
Resolved.
In my case coredns service was not responding. Did not check it before.
Resolved changing default Forward policy:
iptables -P FORWARD ACCEPT

**Comment by debianmaster** [comment]
i have same issue even after `iptales -P FOWARD ACCEPT` any pointers?
Also is there way to get kubeconfig after creating cluster w/o  kubectl vc

**Comment by irmishappy** [comment]
I would start from testing if coreDNS is working as expected. This helped me to find where is a problem.
I assume I used this page for troubleshouting.
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
