### ISSUE TITLE
HNC: allow `kubectl hnc tree` to show _all_ namespaces if no argument is given

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#130]
(Filed as a result of #93)

Currently `kubectl hnc tree` requires an argument, which is the root namespace of the tree to display. We should also allow the user to omit the root argument and print _every_ namespace (and their subnamespaces) instead.

/good-first-issue

**Comment by shivi28** [comment]
hello @adrianludwin I would love to pick this up
