### ISSUE TITLE
HNC: Clean up kubectl plugin hierarchy modification functions

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#131]
(Filed as a part of #93; may supplant #108)

We currently have three commands to change the structure of the hierarchy: `set-parent`, `unset-parent` and `subnamespace`. These commands don't work consistently and aren't grouped well.

As a result, I think we should have a single `set <ns>` command with multiple flags:

- `--parent <parent>`: sets the parent
- `--root`: unsets the parent (i.e., turns this into a root namespace)
- `--requiredChild <child>`: specifies that `<child>` is a required child
- `--unrequiredChild <child>`: **FUTURE** removes the currently unrequired child

I think this is more clear. For example, let's say we have a namespace called `middle` and we wanted to set its parent `top` and its required child `bottom`. Today, this would be expressed as:

```
kubectl hnc set-parent mid top
kubectl hnc subnamespace mid bottom
```

It's not clear, in this setting, what's the meaning of the first or second parameters without looking at the documentation. Instead, the new format will be:

```
kubectl hnc set mid --parent top
kubectl hnc set mid --requiredChild bottom
```
or even:

```
kubectl hnc set mid --parent top --requiredChild bottom --requiredChild otherChild
```

This makes it more clear (I think) which namespace is being acted on and what the resulting relationship will look like. As this example shows, you should be able to set multiple properties in one line as long as they don't conflict (ie `--parent` and `--root`).

Finally, where there's a `set`, there should probably be a `get` as well. Let's change `kubectl hnc show` to `kubectl hnc get` instead.

**Comment by adrianludwin** [comment]
@vjdhama looks like you're not a member of `kubernetes-sigs` yet, can you please add yourself as per https://github.com/kubernetes-sigs/multi-tenancy#join-this-repo? tashimi and I can sponsor you, and it's ok not to have contributions _yet_, just say you'll be working on HNC and reference this issue.

**Comment by vjdhama** [comment]
Thanks. I raised membership request. 🤞
