### ISSUE TITLE
HNC: Package the kubectl plugin for `krew`

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#132]
(Filed as part of #93)

[Krew](https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md) seems to be the recommended way to distribute kubectl plugins. We should package up `kubectl-hnc` as a `krew` plugin.

Also, right now, `make kubectl` puts the binary in `<hnc>/bin` and `<hnc>/devenv` adds it to the path. This means that any other executables in that directory (currently only `manager`) get added to the path as well, which isn't what we want. So we should update `make kubectl` to put the executable in `<hnc>/bin/kubectl` instead and add that to the path when developing.

/good-first-issue

**Comment by shivi28** [comment]
Hello @adrianludwin I would like to pick this issue

**Comment by adrianludwin** [comment]
Just go ahead and assign yourself issues, no need to ask for permission :)

**Comment by adrianludwin** [comment]
This might be helpful: https://elsesiy.com/blog/how-to-kubectl-plugin

@shivi28 , are you actively working on this? If not, can you please unassign yourself so someone else can take it over?

**Comment by shivi28** [comment]
ya sure andrian,  
/unassign @shivi28

**Comment by rjbez17** [comment]
I think for now, until we are stable at least, we'll just want to use the install plugin locally option:

https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md#installing-plugins-locally

Once we have full builds I assume we'll publish a release via github releases and add that to the krew index.

**Comment by adrianludwin** [comment]
+1

**Comment by adrianludwin** [comment]
Reopening because while we're _closer_ to distributing on Krew, we're not actually doing it yet.
