### ISSUE TITLE
HNC: make uninstalling HNC safer

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1320]
Our current guidance to deleting HNC is to delete the CRDs _first_, and rely on the manager to remove their finalizers but _not_ do anything destructive like deleting subnamespaces - which is not always a great assumption (see #1285).

Rather, our guidance should be to remove everything _except_ the CRDs, and then run a client-side tool to remove all finalizers from the CRDs. This has two advantages:

1. No risk of data loss due to bugs like #1285 
2. You can safely uninstall and reinstall HNC using the approved method without losing your hierarchical structure

To make this work requires three steps:

1. Add a label to all HNC components using `kustomize` to make them easier to delete, e.g. "hnc.x-k8s.io: true".
2. Add a command like `kubectl hns config finalize` that removes the finalizers from all HNC anchors and HierarchyConfigurations, allowing namespaces to be deleted.
3. Add instructions to the docs discussing how to safely uninstall HNC: eg remove webhooks, `hnc-system`, then all cluster-level objects using the label from step 1, and then run the tool from step 2.

/good-first-issue

**Comment by yiqigao217** [comment]
/remove-lifecycle stale
@adrianludwin move this to backlog?

**Comment by yiqigao217** [comment]
@adrianludwin
With #1305 doing https://github.com/kubernetes-sigs/multi-tenancy/issues/1285#issuecomment-734384510, seems we don't need this approach of deleting all HNC CRs first and then CRDs, right?

Also, why the step 2 wants `allowing namespaces to be deleted`? Don't we want to prevent data loss?
> To make this work requires three steps:
> 
> 1. Add a label to all HNC components using `kustomize` to make them easier to delete, e.g. "hnc.x-k8s.io: true".
> 2. Add a command like `kubectl hns config finalize` that removes the finalizers from all HNC anchors and HierarchyConfigurations, allowing namespaces to be deleted.
> 3. Add instructions to the docs discussing how to safely uninstall HNC: eg remove webhooks, `hnc-system`, then all cluster-level objects using the label from step 1, and then run the tool from step 2.

**Comment by adrianludwin** [comment]
The idea is that our current process relies on a lot of things to go _well_. E.g. if #1305 has some weird corner case we don't know about, there's a chance of data loss.

So this would be an alternative: first you delete the HNC deployments (to make sure it will _never_ accidentally delete anything), then you remove the finalizers with a separate tool (otherwise _no-one_ will be able to delete them). Finally you delete the CRDs.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/23

/close
