### ISSUE TITLE
HNC: add e2e quickstart test for exceptions

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1324]
I just noticed that we've added a new quickstart section on exceptions but we didn't update the quickstart e2e test. Can you please add this? Thanks!

/assign @GinnyJI

**Comment by yiqigao217** [comment]
/remove-lifecycle stale
Keeping this in 0.8 milestone.

**Comment by GinnyJI** [comment]
Yes, I'm working on this issue
