### ISSUE TITLE
HNC: respect app.kubernetes.io/managed-by

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1328]
HNC currently respects the `hnc.x-k8s.io/managed-by` label on namespaces that it shouldn't attempt to modify, but this is semantically no different than `app.kubernetes.io/managed-by` which is a far more stable standard.

In HNC v0.8, we should stop accepting our own version of managed by and switch to simply accepting the standard version instead. Note that we already _set_ this label on objects propagated by HNC ([docs](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#admin-labels-set)); this new change is about _reading_ this label if it's set on a _namespace_, which HNC will never do.

/assign @GinnyJI

**Comment by yiqigao217** [comment]
Just linking it https://bit.ly/hnc-external-hierarchy for reference.

**Comment by yiqigao217** [comment]
The semantic of `hnc.x-k8s.io/managed-by` annotation and `app.kubernetes.io/managed-by` label is different for HNC. 

There are cases when a namespace has the `app.kubernetes.io/managed-by` label with other manager but doesn't have the `hnc.x-k8s.io/managed-by` annotation with other manager. In this case, HNC can still change the namespace hierarchy or set this namespace as a chlid of another namespace.

For any namespace with the `hnc.x-k8s.io/managed-by` annotation of another manager, HNC cannot set it as a child of another namespace (see [more about this annotation](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#hncx-k8siomanaged-by-annotation-on-namespaces)).

Thus, we will close this issue with no fix and keep the annotation as is.
