### ISSUE TITLE
HNC: detect group automatically where possible

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#1336]
See https://groups.google.com/g/kubernetes-wg-multitenancy/c/g3B9_faG-iY. We insist that users include the API group of any non-core resource, but K8s includes a way to map from unscoped to fully scoped names automatically (I _assume_ only if there isn't a conflict, but I'm not sure).

It would be cool if the `--group` field could (safely) be made optional, either in the CLI or in server-side.

**Comment by smarterclayton** [comment]
Ungrouped names are “first one registered wins” which is mostly to preserve backward compatibility (as we went from ungrouped to grouped).  It can certainly be optional from a client, but any user automating should specify them or risk being broken randomly later.  I don’t think kubectl documents all the gotchas the way it should, but it can at least serve as a guide.

**Comment by adrianludwin** [comment]
Thanks @smarterclayton - I hadn't known that history. I had a mutating admission webhook in mind for the server-side so whatever decision we made was preserved immediately, but on reflection I think that client-side is definitely the way to go as you say, possibly with a warning message.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/24
/close
