### ISSUE TITLE
VC: after some time drops installed dashboard namespace

### ISSUE THREAD

**Issue by irmishappy** [kubernetes-sigs/multi-tenancy#1366]
I am testing dashboard inside VC.
dashboard was installed like:
```
kubeconfigfile=vc-1.kubeconfig
kubectl --kubeconfig $kubeconfigfile apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.4/aio/deploy/recommended.yaml
```
No changes to deployment. 

After ~10h of operation VC seems to restart, and drops newly created namespace.
If no dashboard deployment was installed vc namespaces are available and no restarts noticed during 3 days.

Any hint where to dig?
After instalation:
NAME                   STATUS   AGE
default                Active   4h
kube-node-lease        Active   d4h
kube-public            Active   4h
kube-system            Active   4h
kubernetes-dashboard   Active   3h
After 10+h  :
NAME              STATUS   AGE
default           Active   137m
kube-node-lease   Active   137m
kube-public       Active   137m
kube-system       Active   137m

If I look from master space I see, that default-d96e62-vc-sample-1-kubernetes-dashboard namespace still exists.
etcd-0 and apiserver-0 pods have been restarted.

Any hint where to dig?

**Comment by Fei-Guo** [comment]
Tenant etcd is using in memory datastore (no persistent storage).  If the etcd pod is restarted for some reason, all tenant objects are gone.
