### ISSUE TITLE
[VC] Experimental Scheduler Cluster type generation

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/multi-tenancy#1392]
Looks as though the new cluster type is a copy of the CAPI cluster type - is that meant to be https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/virtualcluster/experiment/pkg/apis/cluster/v1alpha4/cluster_types.go vs https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/cluster_types.go should we just be using these by reference. If it looks like we're getting generated files that haven't been committed when running `make test`.

```bash
→ git status
?? config/crds/cluster.x-k8s.io_clusters.yaml
```

**Comment by Fei-Guo** [comment]
This is intended for easy testing. Another problem is that CAPI does not provide CRD clients so that I have to generate the client manually  which requires the existence of the crd yaml locally. We can clean up this later. 

/close

**Comment by christopherhein** [comment]
Can we at least add the generated yaml from when you run `make test` so that we don't have to exclude it from other PRs?
