### ISSUE TITLE
Is there an option to exclude a resource to propogate?

### ISSUE THREAD

**Issue by vikas027** [kubernetes-sigs/multi-tenancy#1405]
If I have used a secret resource to propagate to all child namespaces, can I control any specific resources to not propagate?
In my use case, there is a secret that I don't want to have in my child namespace.

**Comment by adrianludwin** [comment]
Yes, we introduced this feature in HNC v0.7.0:
https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#basic-exceptions

Please try it out and let us know if you have any questions.

/close
