### ISSUE TITLE
Allow inclusive configuration of resources to propagate

### ISSUE THREAD

**Issue by hferentschik** [kubernetes-sigs/multi-tenancy#1436]
When synchronizing additional resource types, eg Secrets, it is currently only possible to configure this globally (see #1435) and the propagation configuration only allows to exclude certain resources from propagation (via annotation).

It would be nice to have an inclusive way of configuring propagation as well. For example, assume the root namespace contains multiple secrets and I would like to only propagate specific secrets (something like what [reflector](https://github.com/EmberStack/kubernetes-reflector) does). In this case I would like to annotate the Secret to propagate and maybe somehow configure to which child namespaces it should be propagated. 

This might require changing the propagation modes and adding a new one.

**Comment by adrianludwin** [comment]
Yes, this is a good idea and we considered it when we were first [designing exceptions](https://docs.google.com/document/d/17J8icBEDvLLoPT4kQ4ArZcCerRweDY-TpJ48DJKpHJ0):

> In addition, we will consider adding a global `AllowPropagate` mode to `HNCConfig`. This could be useful for types such as Secrets that we don’t want to always propagate. When the propagation mode is `Propagate`, objects will always be propagated unless an annotation is set; in `AllowPropagate`, the reverse is true and the objects will only be propagated if an annotation is set. If we do this, we’ll also a `propagate.hnc.x-k8s.io/all=true` annotation to allow an object to opt into full propagation.

We haven't seen a strong demand from this from our own customers, but I think the interface and semantics are fairly clear so I'd welcome PRs for this feature. Note that the majority of the work here would likely be in coming up with suitable integration tests; the code itself would likely be relatively easy.

/good-first-issue

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/16

/close
