### ISSUE TITLE
InternalError when applying namespace yaml from inside the cluster

### ISSUE THREAD

**Issue by nishanacharya** [kubernetes-sigs/multi-tenancy#1437]
I'm attempting to create a namespace via a Jenkins agent running inside the cluster.

Problem:
Error from server (InternalError): error when creating "some-namespace.yaml": Internal error occurred: failed calling webhook "namespaces.hnc.x-k8s.io": Post https://hnc-webhook-service.hnc-system.svc:443/validate-v1-namespace?timeout=30s: dial tcp 10.99.230.102:443: connect: connection refused

However, if I apply the same namespace yaml configuration from outside the cluster, it gets created without issue and with the correct annotations.

I have seen this in a minikube cluster and a KIND cluster. In both, it works when applied from outside.

**Comment by yiqigao217** [comment]
Hi @nishanacharya what does it mean to apply the namespace from outside the cluster?

From what you described, it seemed you may apply the namespace manifest too fast after installing HNC that the webhooks may not be ready yet. Could you please try applying the namespace manifest 30 seconds after HNC is installed on your failed case?

**Comment by yiqigao217** [comment]
We can reopen this issue if @nishanacharya or anyone else still have this issue.
