### ISSUE TITLE
kubectl hnc set-parent <ns> <parent-ns> command throws error : "the server could not find the requested resource (post hierarchies.hnc.x-k8s.io hierarchy)"

### ISSUE THREAD

**Issue by shivi28** [kubernetes-sigs/multi-tenancy#144]
I created three namespaces :acme-org, team-a and team-b
and when I was trying to set acme-org as parent of team-a using command:

```kubectl hnc set-parent team-a acme-org```

then it throws an error

```Error setting the parent of team-a to acme-org: the server could not find the requested resource (post hierarchies.hnc.x-k8s.io hierarchy)```

**Comment by adrianludwin** [comment]
Fixed by #145
