### ISSUE TITLE
HNC: `propagate.hnc.x-k8s.io/select` won't trigger object propagation on newly labelled namespaces

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1448]
In a namespace hierarchy like this:
```
a
├── [s] b
└── [s] c

[s] indicates subnamespaces
```
If a role in the namespace `a` has
```
    annotations:
      propagate.hnc.x-k8s.io/select: score.networkpolicy/allow-shared-ingress
```
, it won't be propagated into `b` or `c` if they don't have the `score.networkpolicy/allow-shared-ingress` label on the namespace.

The issue is that if we now add `score.networkpolicy/allow-shared-ingress` label to `b` or `c`, the object should be propagated to these namespaces. However currently, the object propagation is not triggered unless there's an update on the source object.

We should make sure the object propagation is triggered when the label is added/removed from a child namespace.

**Comment by adrianludwin** [comment]
Fixed by #1488

/close
