### ISSUE TITLE
HNC: Add excluded namespace configuration to v0.8 release note and installation note.

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1466]
Update the installation note with setting excluded namespaces in v0.8 release note and [here](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/how-to.md#install-or-upgrade-hnc-on-a-cluster).

**Comment by yiqigao217** [comment]
In addition, since we migrated to v1 APIs for CRD, VWH, MWH #1434, we need to add that
- HNC v0.8 requires K8s 1.16+ since only v1.16+ can create v1 webhooks.

**Comment by yiqigao217** [comment]
Just adding another scenario to the doc: what if to exclude a namespace already with subns anchors - see detailed instruction at https://github.com/kubernetes-sigs/multi-tenancy/pull/1483#discussion_r619342311.

**Comment by adrianludwin** [comment]
Hmm, just realized I didn't address the comment for #1483. I'll file a bug to the docs that say "don't do this" :)
