### ISSUE TITLE
HNC: Adapt to new PSP replacement

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1473]
See new [PSP replacement](https://docs.google.com/document/d/1dpfDF3Dk4HhbQe74AyCpzUYMjp4ZhiEgGXSMpVWLlqQ/edit).

The change is about replacing current PSP, which is not namespaced, with namespace labels such as `podsecurity.kubernetes.io/warn=restricted`. The PodSecurityPolicy is deprecated as of Kubernetes v1.21, and will be removed in v1.25.

People will use these new labels to enforce pod security policies per namespace then. Since the label is on namespaces and HNC doesn't propagate labels on a subnamespace, there's no difference of HNC creating a new subnamespace or privileged users creating a new namespace without additional labels. However, users without privileges to create namespaces may not be able to update namespace labels. So we may need to enable them to self-serve namespaces with labels.

**Comment by adrianludwin** [comment]
I'd remove the bit about pods here since we don't consider this to be a
valid use case.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/18
/close
