### ISSUE TITLE
HNC: Update user doc to recommend against propagating workloads

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1474]
Part of #1473 

PSP replacement may affect HNC in that if users use HNC to propagate `pods`, some propagation may fail because of the mismatching pod security policy label on the local child namespace.

HNC can propagate `pods` but we don't recommend it.

Update the user docs to recommend against propagating workloads like `Deployment` `StatefulSet`, etc,

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/19
/close
