### ISSUE TITLE
virtualcluster: Enable olm by default in tenant cluster

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/multi-tenancy#1475]
many end users are now using operator to manage their components, it would be great for the tenant cluster enable OLM by default, then all of the tenant cluster can manage operators by default.

**Comment by Fei-Guo** [comment]
This can be part of the addon support design in Cluster API provider nested (CAPN). CAPN is next generation tenant control plane management framework (https://github.com/kubernetes-sigs/cluster-api-provider-nested). We can discuss the requirement there.

**Comment by gyliu513** [comment]
Thanks @Fei-Guo , opened an issue https://github.com/kubernetes-sigs/cluster-api-provider-nested/issues/41
