### ISSUE TITLE
HNC: Show right namespaces in `kubectl hns tree --all-namespaces`

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1478]
1) Namespaces with conditions are missing in the `kubectl hns tree --all-namespaces` output.
2) Another improvement would be adding additional highlights on excluded namespaces in `kubectl hns` plugins to differentiate the namespaces.

Here's what I got currently:
```
$ kubectl get ns
NAME              STATUS        AGE
default           Active        22h
hnc-system        Active        21h
kube-node-lease   Active        22h
kube-public       Active        22h
kube-system       Active        22h
service-2         Terminating   47m
team-a            Active        47m
team-b            Active        47m


$ kubectl hns tree --all-namespaces  #### team-a and team-b are not listed here
default
hnc-system
kube-node-lease
kube-public
kube-system
service-2

Conditions:
1) ActivitiesHalted (ParentMissing): Parent "acme-org" does not exist


$ kubectl  hns tree team-a
team-a (1)

Conditions:
1) ActivitiesHalted (ParentMissing): Parent "acme-org" does not exist


$ kubectl hns tree team-b
team-b (1)

Conditions:
1) ActivitiesHalted (ParentMissing): Parent "acme-org" does not exist
```

**Comment by FingerLiu** [comment]
multi-tenancy is very useful, I'd like to work on this.
/assign

**Comment by FingerLiu** [comment]
@yiqigao217 since I am new here, would you please give me a hint where should I start?

**Comment by yiqigao217** [comment]
Hi @FingerLiu  sorry for the late reply. The `kubectl hns tree` command are defined in https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/internal/kubectl/tree.go .

Please note only namespaces **with conditions** are not shown in the `kubectl hns tree --all-namespaces`.

**Comment by FingerLiu** [comment]
It looks clear to me know, thanks.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/15

/close
