### ISSUE TITLE
[feat] virtualcluster: Enable different kubernetes distribution support

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/multi-tenancy#1479]
The virtualcluster only support vanila Kubernetes now, but the real use case is that many customers are using some different Kubernetes distributions,  it would be great to enable the virtualcluster can support OpenShift and other Kubernetes clusters which has passed the conformance test at https://github.com/cncf/k8s-conformance/tree/master/v1.20

**Comment by Fei-Guo** [comment]
@gyliu513 Thanks for filing the issue. As you may know, we are actively moving VC project to CAPN (https://github.com/kubernetes-sigs/cluster-api-provider-nested) where we defines the interfaces for using customized APIServer/controller manager/etcd. We are going to integrate CAPN model with existing VC framework shortly. 

When it is ready, one can implement customized nestedapiserver controller to use other kubernetes distribution like k3s/openshift easily.

**Comment by gyliu513** [comment]
Thanks @Fei-Guo that's great! Let me close this one and trace it in https://github.com/kubernetes-sigs/cluster-api-provider-nested
