### ISSUE TITLE
HNC: Add webhook rules to deny editing namespace tree labels

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1494]
Currently, the tree labels on namespaces can be edited without webhook blocking it. HNC will re-reconcile the namespace to update the tree labels.

We need to have our webhooks to block edits on namespace tree labels.

**Comment by adrianludwin** [comment]
Replaced by https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/12

/close
