### ISSUE TITLE
docker pull gcr.io/k8s-staging-multitenancy/hnc-manager:v0.8.0

### ISSUE THREAD

**Issue by admin-zoujing** [kubernetes-sigs/multi-tenancy#1514]
Can you put the image into the local folder to download? This address is very difficult to download.

docker pull gcr.io/k8s-staging-multitenancy/hnc-manager:v0.8.0

**Comment by adrianludwin** [comment]
I'm not sure what you mean by a "local folder?" Docker images are almost
exclusively distributed from a Docker registry like the Docker Hub or gcr.io
.
