### ISSUE TITLE
Could not update the hierarchical configuration of team-a. Reason: the server could not find the requested resource (post hierarchyconfigurations.hnc.x-k8s.io hierarchy)

### ISSUE THREAD

**Issue by onehao** [kubernetes-sigs/multi-tenancy#1517]
the  problem exists in both v0.8.0 and v0.9.0

kubectl-hns version v0.9.0

**Comment by adrianludwin** [comment]
Sorry I missed this. Were you able to figure it out? It looks like the CRDs weren't correctly applied. See if `kubectl get crd` returns anything matching `hnc`.

Please re-open this case if you're still having trouble, but I'll close it for now.

/close

**Comment by adrianludwin** [comment]
Ah - please note that HNC has moved to https://github.com/kubernetes-sigs/hierarchical-namespaces and I'm not monitoring this repo anymore.
