### ISSUE TITLE
Remove HNC managed labels - convert HNC namespace to normal namespace

### ISSUE THREAD

**Issue by jvaibhav123** [kubernetes-sigs/multi-tenancy#1532]
Hi,

We made a mistake in production for one of the namespace which shoudn't be HNC. 
Currently we see all HNC labels on that namespace. When we trying to delete HNC labels, namespace validation webhook is denying that request. We added exclude-namspace argument and added label "hnc.x-k8s.io/excluded-namespace=true" to namespace. I think this will make sure this namespace is not managed by HNC however we would like to get rid of HNC labels.

Is there a way to do that? 

Thanks in advance.

Regards,
Vaibhav Joshi

**Comment by adrianludwin** [comment]
Sorry I missed this. Are you saying that even though the namespace has been excluded, there are still HNC labels on it which you can't remove _after_ having excluded the namespace? That shouldn't happen - if you're still seeing this, can you please include the exact command you wrote, the result of `kubectl get namespace <name> -oyaml` and the result of trying to remove the labels? Thanks!

**Comment by mrbobbytables** [comment]
Repo is to be archived - see https://github.com/kubernetes/org/issues/4297 for details

/close
