### ISSUE TITLE
HNC: validator should reject illegal namespace names

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#172]
Currently `kubectl hnc set foo --requiredChild %^&^%` goes through just fine, though of course the namespace can never be created. We should reject this in the webhook.

**Comment by frbimo** [comment]
hi @adrianludwin , this is my very first PR here, can i pick this one?

**Comment by adrianludwin** [comment]
@frbimo - do you know how validating admission controller webhooks work in K8s? If so, please go right ahead! You're not a member of the kubernetes-sigs organization so I can't assign this issue to you but please feel free to send a PR.

We already have a fair number of new contributors so unfortunately we won't have a lot of time to respond to questions. However, you can try to ping us on the [K8s Slack](https://slack.k8s.io) - @rjbez17 ("Ryan Bez" on Slack) has offered to help out if you get stuck.

**Comment by frbimo** [comment]
@adrianludwin Got it. I will try to ping @rjbez17  first to confirm about this issue. Thank you

**Comment by adrianludwin** [comment]
Fixed by #184
