### ISSUE TITLE
HNC: ns.tree.hnc.x-k8s.io labels are not removed when the hierarchy changes

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#185]
I moved a namespace from one parent to another and noticed that the old namespace label was not removed. The reconciler should remove all existing hnc.x-k8s.io labels (and annotations) when it reconciles a namespace to ensure that old data is cleaned up.

/assign @lafh

**Comment by frbimo** [comment]
@adrianludwin can i pick this issue?

**Comment by adrianludwin** [comment]
Go for it. Note that writing unit tests in hierarchy_controller_test.go
will be an essential part of this task.

**Comment by frbimo** [comment]
@adrianludwin Ok will try to sync with you or @rjbez17 later. 
One question, you said remove "all", means remove even if there are labels other than hnc's label?

**Comment by adrianludwin** [comment]
Fixed via #193
