### ISSUE TITLE
HNC: Reduce the number of times of object propagation

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#189]
See this [discussion](https://github.com/kubernetes-sigs/multi-tenancy/pull/183#issuecomment-546472222).
We need to reduce the number of times we copy objects for no good reason. 

If we introduce hier controller calls into object controllers and thus hier and object controllers can trigger each other, this should speed up the controllers significantly by reducing the unnecessary number of objects and namespaces hier to be reconciled.

The possible implementation could be:
* Don't `updateObjects()` when namespace hier is reconciled if no hier structure changes
* Don't propagate objects again if the source doesn't change.

**Comment by adrianludwin** [comment]
This isn't actually fixed until the new object controller is on by default and the old one is removed.
