### ISSUE TITLE
VC: node controller should backpopulate super master node status

### ISSUE THREAD

**Issue by Fei-Guo** [kubernetes-sigs/multi-tenancy#220]
Currently, tenant master virtual node status is updated periodically by node controller which is not efficient. We should watch for super master node status change and back populate to tenant master.

**Comment by zhuangqh** [comment]
If we back populate the node status from super master to tenant, we should maintain a table that records which node belongs to which tenant. And then update the status.
The overhead of this solution may heavier?

We could using node lease to update the node status

**Comment by zhuangqh** [comment]
I'll take it
