### ISSUE TITLE
Clarification: Regarding TenantTemplate CR in  the documentation

### ISSUE THREAD

**Issue by rkamudhan** [kubernetes-sigs/multi-tenancy#23]
In the document [Kubernetes Tenant CRD](https://docs.google.com/document/d/1hpJX5O_siMmNGMvIHvz8Pm7XOjJLz5g57XWrgwWarFw/edit#heading=h.x4zvfw13hjli)

Advanced (Full) Version Workflow:
- A cluster-admin creates and defines one or more TenantTemplate-CR and NamespaceTemplate-CR objects in a cluster.
- A TenantTemplate-CR instance may itself refer to one or more NamespaceTemplate-CR objects.
- A tenant-instance-admin will be able to view the available list of TenantTemplate-CR instances that are made readable to him/ her by the cluster-admin.
- A tenant-instance-admin can then synchronously create one or more Tenant-CR objects using one of the TenantTemplate-CR objects available to him. This is referred to as the synchronous model of tenant creation.

Is there any example for the tenantTemplate-CR ? How the cloud admin use it to create one or more tenant-CR ?

**Comment by easeway** [comment]
Replied after your comment in the original doc:

> TenantTemplate CR is currently not defined/implemented yet. It's actually a convenient mechanism for tenant admin to create a Tenant CR without specifying everything. Today, as there's really not too many things in Tenant CR, we don't plan to define/implement TenantTemplate CRD.
