### ISSUE TITLE
VC: kubernetes conformance test for tenant

### ISSUE THREAD

**Issue by zhuangqh** [kubernetes-sigs/multi-tenancy#250]
set up a k8s e2e test for tenant to figure out whether the virtual cluster looks like a real k8s cluster.

Summarizing 35 Failures:

- [x]   [Fail] [k8s.io] InitContainer [NodeConformance] [It] should not start app containers if init containers fail on a RestartAlways pod [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:292

- [x] [Fail] [sig-storage] ConfigMap [It] updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/configmap_volume.go:188

- [x]  [Fail] [sig-node] Downward API [It] should provide pod name, namespace and IP address as env vars [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2342

- [x] [Fail] [k8s.io] Pods [It] should allow activeDeadlineSeconds to be updated [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:439

- [x] [Fail] [k8s.io] InitContainer [NodeConformance] [It] should invoke init containers on a RestartNever pod [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:99

- [x] [Fail] [sig-storage] Secrets [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/secrets_volume.go:367

- [x] [Fail] [sig-storage] Projected secret [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_secret.go:401

- [x] [Fail] [sig-storage] Downward API volume [It] should update annotations on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:181

- [x] [Fail] [k8s.io] InitContainer [NodeConformance] [It] should invoke init containers on a RestartAlways pod [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:170

- [x] [Fail] [sig-storage] Projected downwardAPI [It] should update annotations on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_downwardapi.go:181

- [x] [Fail] [sig-storage] Projected downwardAPI [It] should update labels on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_downwardapi.go:147

- [x] [Fail] [sig-storage] Projected configMap [It] updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_configmap.go:194

- [x] [Fail] [sig-storage] ConfigMap [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/configmap_volume.go:466

- [x] [Fail] [k8s.io] InitContainer [NodeConformance] [It] should not start app containers and fail the pod if init containers fail on a RestartNever pod [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:401

- [x] [Fail] [sig-storage] Downward API volume [It] should update labels on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:147

- [x] [Fail] [sig-storage] Projected configMap [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_configmap.go:394

- [x] [Fail] [sig-cli] Kubectl client [k8s.io] Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2056

- [x] [Fail] [k8s.io] Kubelet [AfterEach] when scheduling a busybox command in a pod should print the output to logs [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:335

- [x] [Fail] [k8s.io] Pods [It] should be submitted and removed [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:307

- [x] [Fail] [k8s.io] [sig-node] PreStop [It] should call prestop when killing a pod  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pre_stop.go:161

- [x] [Fail] [k8s.io] [sig-node] Pods Extended [k8s.io] Delete Grace Period [It] should be submitted and removed [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pods.go:163

- [ ] [Fail] [k8s.io] Pods [It] should support retrieving logs from the container over websockets [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:674

- [x] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [x] [Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [x] [Fail] [sig-network] DNS [It] should provide DNS for ExternalName services [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [x] [Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] Should recreate evicted statefulset [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/statefulset.go:769

- [x] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [x] [Fail] [sig-api-machinery] Aggregator [It] Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:391

- [x] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: http [LinuxOnly] [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [x] [Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [x] [Fail] [sig-auth] ServiceAccounts [It] should mount an API token into pods  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/service_accounts.go:237

- [x] [Fail] [k8s.io] [sig-node] Events [It] should be sent by kubelets and the scheduler about pods scheduling and running  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/events.go:96

- [x] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: http [LinuxOnly] [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [ ] [Fail] [sig-network] DNS [It] should provide /etc/hosts entries for the cluster [LinuxOnly] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [x] [Fail] [sig-network] Proxy version v1 [It] should proxy logs on node with explicit kubelet port using proxy subresource  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:313

**Comment by zhuangqh** [comment]
Summarizing 35 Failures:

- [ ]   [Fail] [k8s.io] InitContainer [NodeConformance] [It] should not start app containers if init containers fail on a RestartAlways pod [Conformance]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:292

- [ ] [Fail] [k8s.io] Pods [It] should support retrieving logs from the container over websockets [NodeConformance] [Conformance]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:674

- [ ] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [ ] [Fail] [sig-storage] ConfigMap [It] updates should be reflected in volume [NodeConformance] [Conformance]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/configmap_volume.go:188

- [ ]  [Fail] [sig-node] Downward API [It] should provide pod name, namespace and IP address as env vars [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2342

- [ ] [Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] Should recreate evicted statefulset [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/statefulset.go:769

- [ ] [Fail] [sig-cli] Kubectl client [k8s.io] Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2056

- [ ] [Fail] [k8s.io] Pods [It] should be submitted and removed [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:307

- [ ] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [ ] [Fail] [k8s.io] [sig-node] PreStop [It] should call prestop when killing a pod  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pre_stop.go:161

- [ ] [Fail] [k8s.io] [sig-node] Pods Extended [k8s.io] Delete Grace Period [It] should be submitted and removed [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pods.go:163

- [ ] [Fail] [k8s.io] Pods [It] should allow activeDeadlineSeconds to be updated [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:439

- [ ] [Fail] [k8s.io] InitContainer [NodeConformance] [It] should invoke init containers on a RestartNever pod [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:99

- [ ] [Fail] [sig-storage] Secrets [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/secrets_volume.go:367

- [ ] [Fail] [sig-storage] Projected secret [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_secret.go:401

- [ ] [Fail] [sig-api-machinery] Aggregator [It] Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:391

- [ ] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: http [LinuxOnly] [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [ ] [Fail] [sig-storage] Downward API volume [It] should update annotations on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:181

- [ ] [Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [ ] [Fail] [sig-auth] ServiceAccounts [It] should mount an API token into pods  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/service_accounts.go:237

- [ ] [Fail] [k8s.io] [sig-node] Events [It] should be sent by kubelets and the scheduler about pods scheduling and running  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/events.go:96

- [ ] [Fail] [k8s.io] InitContainer [NodeConformance] [It] should invoke init containers on a RestartAlways pod [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:170

- [ ] [Fail] [sig-storage] Projected downwardAPI [It] should update annotations on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_downwardapi.go:181

- [ ] [Fail] [k8s.io] Kubelet [AfterEach] when scheduling a busybox command in a pod should print the output to logs [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:335

- [ ] [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: http [LinuxOnly] [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:659

- [ ] [Fail] [sig-network] DNS [It] should provide /etc/hosts entries for the cluster [LinuxOnly] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [ ] [Fail] [sig-network] Proxy version v1 [It] should proxy logs on node with explicit kubelet port using proxy subresource  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:313

- [ ] [Fail] [sig-storage] Projected downwardAPI [It] should update labels on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_downwardapi.go:147

- [ ] [Fail] [sig-network] DNS [It] should provide DNS for ExternalName services [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [ ] [Fail] [sig-storage] Projected configMap [It] updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_configmap.go:194

- [ ] [Fail] [sig-storage] ConfigMap [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/configmap_volume.go:466

- [ ] [Fail] [k8s.io] InitContainer [NodeConformance] [It] should not start app containers and fail the pod if init containers fail on a RestartNever pod [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/init_container.go:401

- [ ] [Fail] [sig-storage] Downward API volume [It] should update labels on modification [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:147

- [ ] [Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:510

- [ ] [Fail] [sig-storage] Projected configMap [It] optional updates should be reflected in volume [NodeConformance] [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected_configmap.go:394

**Comment by zhuangqh** [comment]
waiting https://github.com/kubernetes/kubernetes/pull/86071 to be merged
the e2e test cannot recognize the custom kubelet port

**Comment by ShadowJonathan** [comment]
@zhuangqh

**Comment by ShadowJonathan** [comment]
@zhuangqh can I get some response to this issue rotting?
