### ISSUE TITLE
MTB: add test for Block modification of multi-tenancy resources (MTB-PL1-BC-CPI-2)

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/multi-tenancy#259]
Add automated test case for:

https://github.com/kubernetes-sigs/multi-tenancy/tree/master/benchmarks/e2e/tests/block_multitenant_resources

**Comment by phoenixking25** [comment]
@JimBugwadia  Need some help in the cmd you mentioned i.e.
`kubectl --kubeconfig=tenant-a -n a1 get all -l <key>=<value> `
And above this mentioned to run this as cluster-administrator, so i think there's some conflict.
`Run the following commands to retrieve the list of resources managed by the cluster administrator`

**Comment by JimBugwadia** [comment]
closing as the project is being restructured
