### ISSUE TITLE
VC: provide a config, enable tenant to use super master's CA

### ISSUE THREAD

**Issue by zhuangqh** [kubernetes-sigs/multi-tenancy#273]
If pod required to access its own apiserver, the tenant apiserver should use the same root CA as the super master one. Because the CA in service account token is always the super master one, the client fails to pass the authentication if it not do so.

@charleszheng44

**Comment by Fei-Guo** [comment]
@charleszheng44 can you take it?

**Comment by zhuangqh** [comment]
/close
unnecessary
