### ISSUE TITLE
HNC: Add more test cases to object_controller_test.go

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#278]
Since we changed the behavior of the object controller, we need to add more test cases:
1) It should be propagated to all descendants if a source object is changed
2) It should be overwritten if a propagated object is changed

**Comment by adrianludwin** [comment]
@yiqigao217 Do you think we still need these additional tests?

**Comment by yiqigao217** [comment]
I looked up int the current `object_test.go`. These tests are already added.
