### ISSUE TITLE
HNC: Store source objects by GK in the forest

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#281]
Currently, the source objects in the forest are stored by GVK:
`type objects map[schema.GroupVersionKind]map[string]*unstructured.Unstructured`
Since users can deal with the same object with different versions, the identifier here should just be Group and Kind.

**Comment by adrianchung** [comment]
I'm going to be picking this issue up

**Comment by adrianludwin** [comment]
/close

We decided not to do anything more in #589.
