### ISSUE TITLE
Update Tenant Controller to use Hierarchical Namespace Controller 

### ISSUE THREAD

**Issue by tashimi** [kubernetes-sigs/multi-tenancy#300]
HNC+Tenant Operator

Based on Fei Guo’s (Alibaba) design to integrate HNC and Tenant
Operator (https://docs.google.com/document/d/1QAWtYdRZGseSar_KgyfiIisL7JTGMHCfqB_Legfa39w/edit#heading=h.7wst4safj8dx)

Weeks 1-3: Install Tenant Operator and generate a set of (manual) test cases

Weeks 4-6: Create a branch of the Tenant Operator, remove its object
propagation code, and instead have it generate Hierarchical Namespace
Controller CRDs.

Weeks 7-9: Set up a joint CI system for the Tenant Operator that
includes pulling in the Hierarchical Namespace Controller releases.

Weeks 10-12: Test and document extended use cases (eg Tenant Operator
plus self-service namespaces)

Weeks 13-15: Improve Hierarchical Namespace Controller configurability
for Tenant Operator use cases

Weeks 16-18: wrapup any remaining work, open issues for anything
further to be done, present work to the working group at their regular
meeting

**Comment by VineethReddy02** [comment]
Hey @tashimi 
I have noticed this project under community bridge program. I would love to work on this project. Is someone else is working on this? If not can I pick some good first issues and start working on this?

**Comment by tashimi** [comment]
Hi @VineethReddy02 - @shivi28 is already working on this project. I can put together another proposal for a project if you're interested in working on multi-tenancy.

**Comment by VineethReddy02** [comment]
@tashimi yeah sure. I am interested to work with multi-tenancy. As December 16 is deadline for finalising the projects. I can start working if project is put in place.

Thanks! :)
