### ISSUE TITLE
Update HNC CLI to matching naming doc

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#302]
Implement bit.ly/hnc-cli-naming

/assign @adrianludwin

**Comment by VineethReddy02** [comment]
Hi @adrianludwin 
If you are okay. I can pick this up and update ```kubectl hnc``` plugin as mentioned in hnc-cli-naming doc.

**Comment by adrianludwin** [comment]
Thanks @VineethReddy02 but there's a fair amount of context that was needed to implement this stuff, so it was easier to do it myself.
