### ISSUE TITLE
Add label aggregation and overrides to HNC 

### ISSUE THREAD

**Issue by tashimi** [kubernetes-sigs/multi-tenancy#303]
Add [label propagation](https://docs.google.com/document/d/10MZfFfbQMm33CBboMq2bfrEtXkJQQT4-UH4DDXZRrKY/edit#heading=h.z6soyqp0ld0z) and [overrides](https://docs.google.com/document/d/10MZfFfbQMm33CBboMq2bfrEtXkJQQT4-UH4DDXZRrKY/edit#heading=h.4el9m8gv8fqy).

Weeks 1-3: Implement basic namespace label+annotation propagation
Weeks 4-6: Object overrides: create label and obey it
Weeks 7-9: Object overrides: create webhook to deny access
Weeks 10-12: Object overrides: test cases
Weeks 13-15: NS labels: allow overrides
Weeks 16-18: wrapup

**Comment by Masquerade0097** [comment]
Hi @tashimi, I would like to work on this issue as part of community bridge. Please let me know If I can start working on it?

**Comment by VineethReddy02** [comment]
Hi @tashimi 
Thanks for putting together another proposal on my interest. I went through the design doc.
what do you suggest in getting started with this feature?

**Comment by arijeet-majumdar** [comment]
Hello Tashimi, 
I would also like to join in as part of the bridge program. 

Thanks and Regards
Arijeet

**Comment by tashimi** [comment]
Hey all - 
It looks like we won't have the bandwidth to provide the needed architectural and mentorship guidance on this issue for this round of the bridge program. Closing this issue for now, and we'll try again some other time.
