### ISSUE TITLE
Publish kubectl-hnc to krew(official kubectl plugin manager).

### ISSUE THREAD

**Issue by VineethReddy02** [kubernetes-sigs/multi-tenancy#304]
I think we can publish kubectl hnc to krew plugin manager for easy installation and easy access to everyone.

Any suggestions? @tashimi

**Comment by adrianludwin** [comment]
Sorry @VineethReddy02 , I missed this. Can you explain a bit more about the process here? When we make a new release, how do we update Krew?

**Comment by adrianludwin** [comment]
See also #132

**Comment by VineethReddy02** [comment]
So when I wanted to use ```kubectl hnc``` I had a hard time building ```kubectl-hnc``` from scratch & also helps in visibility alongside of other kubectl plugins. May be publishing it to ```krew``` would make it easier.
Here are the steps to publish new plugin to krew https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md.

**Comment by adrianludwin** [comment]
That's definitely on the roadmap. I'm *just* about to publish and update
the README, as well as an enhanced build process, that will create official
kubectl plugin images (that was the first step). We can get it into Krew
next.

**Comment by adrianludwin** [comment]
See #332
