### ISSUE TITLE
HNC: `kubectl hns create` should fail if the namespace already exists

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#309]
Currently, `kubectl hns create` is a synonym for `kubectl hns set --requiredChild`, but while the latter is (marginally) acceptable if the namespace already exists, the former is not. We should check whether the namespace exists and fail if it does.

**Comment by vjdhama** [comment]
@adrianludwin If you don't mind I would like to help with this.

**Comment by adrianludwin** [comment]
Go for it!

**Comment by adrianludwin** [comment]
/unassign @vjdhama 
/assign @yiqigao217 

Yiqi, does your new kubectl code handle this?

**Comment by yiqigao217** [comment]
No, not yet. This will be implemented with the webhook since the new `k hns create` will create a new HNS instance instead of setting the previous '--reqiredChild` field. See #458

**Comment by adrianludwin** [comment]
Sorry, that's what I meant - the new code _will_ handle this. Thanks!

/close

**Comment by yiqigao217** [comment]
Sorry that I'm confused. I think we still need something similar to webhook to enforce it. Since currently, the new 'create' can create an HNS with an existing namespace name.

**Comment by adrianludwin** [comment]
Yup, we definitely need the webhook, we just don't need anything in the kubectl plugin.

**Comment by yiqigao217** [comment]
> Yup, we definitely need the webhook, we just don't need anything in the kubectl plugin.

Ah agreed.
