### ISSUE TITLE
HNC: prevent reconciling hnc-system and other default namespaces

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#318]
Currently, the Hierconfig and Object controllers reconcile all the default namespaces (`kube-system`, `hnc-system`, etc.) and the objects inside. Some of those objects change all the time, which triggers the object controllers to reconcile them constantly. One example is `hnc-system/controller-leader-election-helper`.

We can make changes to the controllers to only reconcile objects in the user-created namespaces.

**Comment by adrianludwin** [comment]
@yiqigao217 This is done now, right?

**Comment by yiqigao217** [comment]
Yes, by `Ex` map.
