### ISSUE TITLE
Tide and GitHub settings for this repo are conflicting.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes-sigs/multi-tenancy#33]
https://prow.k8s.io/tide-history?repo=kubernetes-sigs%2Fmulti-tenancy

> Tide needs to be configured to use the 'rebase' merge method for this repo or the repo needs to allow merge commits: Merge commits are not allowed on this repository.

Please change the GitHub settings for the repo to allow merge commits or [configure Tide](https://github.com/kubernetes/test-infra/blob/28f7c583609c7d63822fb2cb4ab7dfb6ad1fab1a/prow/config.yaml#L429-L448) to use the `rebase` merge method ASAP to allow PRs to merge and avoid wasting GitHub API ratelimit.

**Comment by rjbez17** [comment]
@tashimi I don't have admin privileges for this repo, can you configure to allow merge commits?

**Comment by tashimi** [comment]
Done! 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/719646/62386366-7e04f580-b50c-11e9-947c-d4daf3c31fc4.png">

**Comment by cjwagner** [comment]
We need to enable `merge` commits in the GH settings, `rebase` should have already been checked based on the error message.
The alternative was to configure *Tide* for `rebase` commits (not GH).

We need the configs to match and currently Tide is configured to use merge commits (the default).

**Comment by tashimi** [comment]
@cjwagner Is this what you're looking for?

<img width="802" alt="image" src="https://user-images.githubusercontent.com/719646/62398052-72292b80-b52c-11e9-859d-7c05a3a9904d.png">

**Comment by cjwagner** [comment]
That should do it, thanks.
/close
