### ISSUE TITLE
VC: ignore object labels which were set by super master controller

### ISSUE THREAD

**Issue by zhuangqh** [kubernetes-sigs/multi-tenancy#330]
tenant's Pods in super master may be attached some label by super master controller.
We should ignore these label when computing the diff of pPod and vPod.

**Comment by zhuangqh** [comment]
Implement tips
1. create a flag to receive a slice of string prefix, which would be used to filter object label or annotations. may named 'standalone-object-annotation-prefixes'
2. change the kvequality checker here https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/virtualcluster/pkg/syncer/conversion/equality.go#L108
3. find a way this pass the prefix parameters to the EqualityChecker.
I prefer firstly create a context object, then do equality check. The user interface like
`Syncer(prefix parameter).CheckEquality(pPod, vPod)`  because there are many place use this func.

`CheckEquality(config, pPod, vPod)` this design worse


if the key match the prefix, just ignore this key. Let this key control by their master independently.

**Comment by zhuangqh** [comment]
@charleszheng44

**Comment by charleszheng44** [comment]
PR #389
