### ISSUE TITLE
HNC: release should not re-push an existing image by default

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#333]
See https://github.com/kubernetes-sigs/multi-tenancy/pull/332#discussion_r360651870. By default, the release should refuse to push an image if it already exists on the repo, although we'll need a way to override (eg to push :latest or to test).

**Comment by adrianchung** [comment]
My plan here is to disallow releasing if an image and tag already exists for the resolved tag. There will be a FORCE_RELEASE flag that can be set to override this for test/bad push purposes.

**Comment by adrianludwin** [comment]
Fixed by #576 

/close
