### ISSUE TITLE
HNC: propagate deleted source when conditions are gone

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#347]
Currently when critical conditions are cleared for a namespace, the previously paused deletion of an object will not propagate to children namespaces.

The issue is that since there’s a critical condition in the namespace, the `syncDeletedSource()` is skipped. What the `syncDeleteSource()` func does is deleting the source in the forest and enqueuing all descendant copies.

Since the source is never deleted in the forest, even when the critical conditions are gone for the namespace, the should-be-deleted propagated objects are still consistent with the forest thinking that the source is still there in the ancestor by looking at the forest. The source in the forest will never be deleted because the real object has been deleted and will never be reconciled again to sync with forest.

**Comment by adrianludwin** [comment]
@yiqigao217 Is this still an open issue?

**Comment by yiqigao217** [comment]
I tested manually again and it's still an open issue. Here's my testing:
`k create ns zparent`
`k create ns zchild`
`k create ns zgrand`
`k hns set zchild --parent zparent`
`k hns set zgrand --parent zchild`
`k hns tree zparent`
zparent
|__zchild
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |__zgrand
`k -n zchild create configmap configmap-zchild --from-literal key=value`
The source is created in `zchild` and it's propagated to `zgrand`.
`k delete ns zparent`
This causes `zchild` and `zgrand` to have `CRIT` condition. `zgrand` got msg 'Propagation paused in the subtree of zchild due to a critical condition'
`k delete configmap configmap-zchild -n zchild`
The propagated `configmap-zchild` in `zgrand` is not deleted as expected.
`k create ns zparent`
Now the `CRIT` conditions are all gone, but the propagated `configmap-zchild` in `zgrand` is still there.

**Comment by adrianludwin** [comment]
Thanks, I'll look at this along with #328

**Comment by adrianludwin** [comment]
Here's what _should_ be happening here:
* The critical condition is removed, and all descendents are enqueued
* As each descendent is reconciled, it notices that it changed, so it calls `updateObjects`
* In `updateObjects`, it should notice that the `configmap-zchild` needs to be deleted

Currently looking into why this isn't happening.

**Comment by adrianludwin** [comment]
Ah - when there's a crit condition, we skip the entire object reconciler so we never update the forest to know that the object's been removed. This doesn't seem right - we should only skip _actions_ if there's a crit condition, not our internal reflection of the apiserver state.

**Comment by adrianludwin** [comment]
Fixed by #574 

/close
