### ISSUE TITLE
HNC: make client QPS limit configurable and set default limit at 50QPS

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#369]
We discovered that HNC is very slow because the default client-go library limits you to 5 QPS by default with a burst rate of 10. This is very, very low if you have to sync a large number of namespaces, as will typically be the case for HNC.

We should make this configurable and set a good default limit. On GKE, apiservers for small clusters have a limit of 100QPS, and I observed unfortunate things happening when I drove HNC to this level (eg leader election started failing elsewhere on the cluster). So I'm going to propose a default of 50QPS, with the burst set to 50% higher than that (eg 75QPS).

**Comment by adrianludwin** [comment]
@sophieliu15 - see this line: https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/cmd/manager/main.go#L73

```
mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
```

The config returned by `GetConfigOrDie` is what we need to modify. Something like this:

```
cfg := ctrl.GetConfigOrDie()
cfg.QPS = 50
cfg.Burst = cfg.QPS * 1.5
```

except instead of hardcoding these values, we should read them from a flag, and then set the default here: https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/config/default/manager_auth_proxy_patch.yaml#L23

**Comment by adrianludwin** [comment]
@rjbez17 Do you think we should hardcode an upper limit in HNC itself? Or just let people shoot themselves in the foot if they really want to (plus other K8s clusters might have a higher limit than small GKE clusters)?

**Comment by rjbez17** [comment]
I generally think shooting yourself in the foot is fine if it’s clear what I used to do it with.

Basically, if we can identify that we are having issues because too high QPS and we log it, that’s totally enough in my opinion.

**Comment by adrianludwin** [comment]
sgtm, thanks.

**Comment by adrianludwin** [comment]
This is now done

/close
