### ISSUE TITLE
Final review of multi-tenancy proposal

### ISSUE THREAD

**Issue by tashimi** [kubernetes-sigs/multi-tenancy#4]
Draft a proposal of the work the multi-tenancy working group is going to tackle, and present it to the working group for feedback and approval.

 https://docs.google.com/document/d/1U8RQQmTUjxgMZY05HG2f7b3KsB94BhK4Ko6aWbLNXcc/edit#heading=h.usecunpmfu3a

**Comment by rkamudhan** [comment]
@tashimi Please correct me, if I missing the following use case. 

My use case is that, I am having 3 department in my office, each department can have 4 tenant or client in them. From the proposal, I can see that one Kubernetes namespace represent one tenant. Is there any logical representation of department in the use case. Is there any mechanism, we can address one layer hierarchy above tenant on this using tenant crd annotation or including a field in the tenant crd
