### ISSUE TITLE
HNC: export from OpenCensus to Prometheus

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#416]
cc @rjbez17 @yiqigao217 

As of #410, HNC is now able to exporting metrics to Stackdriver. It doesn't yet support Prometheus because:

1. None of us HNC developers were able to install and configure Prometheus in a reasonable amount of time; 
2. We couldn't figure out how to get OpenCensus' Prometheus endpoint to play nicely with controller-runtime's Prometheus endpoint. Maybe we can expose them on different ports?

For anyone with Prometheus experience, it's probably fairly easy to fix this problem but we don't currently have the expertise to do it ourself.

/good-first-issue

**Comment by rjbez17** [comment]
Sounds like I can actually be useful! I'll try to take a wack at this next week.

**Comment by yeya24** [comment]
@rjbez17  Hi, I think I can work on this issue this week. Is it okay?

**Comment by rjbez17** [comment]
I’ll never complain about someone doing work for me faster than me! Go for it

**Comment by yeya24** [comment]
I am checking this issue now. But I am wondering what metrics do we have currently? If we don't have any metrics except the metrics from controller-runtime, why we need to add Prometheus?

**Comment by adrianludwin** [comment]
Hi Ben, have you worked with metrics and Prometheus before?

We have metrics exported from controller-runtime on a Prometheus endpoint,
and also from OpenCensus via Stackdriver (see
https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/pkg/stats/metrics.go).
We'd like to also export from OpenCensus to Prometheus, but without
disrupting the endpoint from controller-runtime. Does that all make sense?
If not, it's probably not a good starter project on HNC since this area is
quite complicated if you don't already know all these monitoring systems.
Thanks!

**Comment by yeya24** [comment]
@adrianludwin  Hi, so you want to add the metrics from Stackdriver to the /metrics endpoint exposed by controller-runtime?

**Comment by adrianludwin** [comment]
If possible, yes. Otherwise, we'd like to expose a *second* /metrics
endpoint (e.g. on another port) and have instructions for how to configure
Prometheus to use both.

**Comment by yeya24** [comment]
Yes, I have implemented this to use the same /metrics. But I am not familiar with StackDriver so I am not sure whether it works or not. I don't have an env for testing

**Comment by adrianludwin** [comment]
Cool - maybe throw up a PR and we can see if StackDriver is still working?

**Comment by yeya24** [comment]
PR opened, check #432

**Comment by adrianludwin** [comment]
Thanks! I'll leave further comments there.
