### ISSUE TITLE
Get official container registry from #wg-k8s-infra

### ISSUE THREAD

**Issue by rjbez17** [kubernetes-sigs/multi-tenancy#43]
We need to move from docker hub to an official k8s sig registry. Info from @kfox1111  here:

https://github.com/kubernetes-sigs/multi-tenancy/pull/42#issuecomment-524025857

**Comment by tashimi** [comment]
From @kfox1111: 

> Looks like #wg-k8s-infra can hook us up with gce.
> 
> "first step is to create a google group for the access control for the repo (please add one in https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml) and then an entry in the script for creating the staging repo (please update https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/ensure-staging-storage.sh#L41). Please see older PR(s) that were merged when in doubt."

@kfox1111 : @Fei-Guo indicated that GCE is not a good tool for non-US based developers, which is why he was asking for a docker hub account. Can we discuss this before we go ahead and get this account?

**Comment by rjbez17** [comment]
Aren't all kubernetes core images pushed to k8s.grc.io? Do they have a mirror somewhere? I have to image this issue has been resolved by other sigs? I'll reach out to #wg-k8s-infra to see what our options are.

**Comment by kfox1111** [comment]
Hmm... part of the setup of the repo mentions the repo syncing into:
- name: asia.gcr.io/k8s-artifacts-prod/multitenancy

Is that accessible @Fei-Guo?

**Comment by Fei-Guo** [comment]
> Hmm... part of the setup of the repo mentions the repo syncing into:
> 
> * name: asia.gcr.io/k8s-artifacts-prod/multitenancy
> 
> Is that accessible @Fei-Guo?

gcr.io is completely blocked in china as far as I know.

**Comment by kfox1111** [comment]
I don't know how accurate it is, but:
https://viewdns.info/chinesefirewall/?domain=asia.gcr.io

Says it is accessible. Have you tried it?

**Comment by rjbez17** [comment]
I reached out to #wg-k8s-infra to confirm whether or not asia.gcr.io is accessible from china. If they don't know we'll have to find someone within the community to test it for us.

**Comment by kfox1111** [comment]
https://github.com/kubernetes/k8s.io/pull/343 Just merged.

**Comment by adrianludwin** [comment]
Is this done?

**Comment by rjbez17** [comment]
Completed
