### ISSUE TITLE
HNC: About the Hierarchical ResourceQuota support

### ISSUE THREAD

**Issue by thincal** [kubernetes-sigs/multi-tenancy#439]
There is one use case about the quota usecase in multiple layered tenancy (HNC) detailed as bellow:

```
tenant (100 GPU)
 |
 +--> department-a (50 GPU)
          |
          +---> user1 (share)
          +---> user2 (<= 10 GPU)
```
tenant admin will statically allocate 50GPU quota for department-a, but:
- user1 under the department will share the department quota
- user2 will be ~~allocated~~ limited with a dedicated 10 GPU

so that any resource created under one user (namespace) needs to check the available resources constrains from itself or parent department, with current ResourceQuota model it doesn't work with this case.

Similar with the hierarchical namespace for multi-tenancy, is that possible to create hierarchical resourceQuota controller for validating quota request ?

and any thoughts / suggestion for this case ?

**Comment by JimBugwadia** [comment]
A team from IBM had presented a solution for quota management across namespaces at a multi-tenancy WG meeting. There was discussion of adding HNC support. You can check out the video at: https://www.youtube.com/watch?v=V0Zw82nOAEE&feature=youtu.be.

**Comment by rjbez17** [comment]
This is a known limitation. HNC only replicates resources. It does not do any logic about the things being replicated to children.

We’ve discussed adding support for this in HNC around ResourceQuotas but don’t have a timeframe for support.

**Comment by thincal** [comment]
@rjbez17 

> We’ve discussed adding support for this in HNC around ResourceQuotas

Could you share the discussion results or draft idea around this support ?

**Comment by thincal** [comment]
@JimBugwadia thanks for sharing, it looks like the solution presented doesn't consider and handle the "hierarchical" well yet.

**Comment by adrianludwin** [comment]
There have just been a series of "this seems like it would be nice" discussions, plus the one we had with IBM.

@thincal , can you share anything more about your usecase? Eg can you say anything about the company you work for, how many levels of hierarchy you expect to have, what kinds of quotas you want to set, etc?

**Comment by adrianludwin** [comment]
We're certainly open to contributions if you want to put together a proposal. It's not a priority for us right now but that doesn't mean we can't review others' contributions!

**Comment by ShadowJonathan** [comment]
@rjbez17 @adrianludwin any update on this?

**Comment by adrianludwin** [comment]
No, I was hoping for some additional information from @thincal , but regardless, I don't think anyone's signed up to do the work. If you'd like to volunteer we'd be happy to work with you!

**Comment by adrianludwin** [comment]
@just1900 are you interested in working on this problem? We've had a few people ask for it but until someone's signed up to work on it, I don't think there's much point re-opening the bug.
