### ISSUE TITLE
HNC: Implement self-service namespace

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#457]
Allow tenant admins who do not have cluster-wide namespace creation privileges to still create subnamespaces by creating custom resource instances locally. 

The implementation includes:
* Define `HierarchicalNamespace` (`hns`) CRD
* Add `allowCascadingDelete` field to `HierarchyConfig.spec`
* Add `kubectl` plugin to toggle `HierarchyConfig.spec.allowCascadingDelete`
* Create an HNS reconciler to create/delete subnamespaces, interact with HC reconciler, etc. 
* Add webhook on the creation of HNS
* Add `kubectl` plugin to create an HNS

See design: [HNC self-service namespaces UX](http://bit.ly/hnc-self-serve-ux)

**Comment by adrianludwin** [comment]
I think we're done with this? Congrats!

**Comment by yiqigao217** [comment]
> I think we're done with this? Congrats!

Thanks! The only thing left is the flaky test #560 . As for `EX` map, I unlinked the issue #495  to this main issue.

**Comment by adrianludwin** [comment]
I think you can close this one, the hnc-v0.3 milestone is sufficiently
tracking IMO.

**Comment by yiqigao217** [comment]
I see, sure!
