### ISSUE TITLE
HNC: Avoid restart HNC after adding a new CRD

### ISSUE THREAD

**Issue by sophieliu15** [kubernetes-sigs/multi-tenancy#488]
Right now when HNC is running and we add a new CRD and hope to config the new type, there are two problems:
- Reconciliation of `ConfigReconciler` will not be triggered automatically. We need to change `config` object to trigger reconciliation.
- Even after manually triggering the reconciliation from `ConfigReconciler`, `ObjectReconciler` will not recognize the CRD and as a result corresponding object reconciler cannot be created.

In order to create the object reconciler for the new type, we need to kill the manager pod to restart HNC. We should either avoid restarting HNC after adding a new CRD, or prevent users from adding a new CRD after starting HNC.

**Comment by sophieliu15** [comment]
Discussion here: https://github.com/kubernetes-sigs/multi-tenancy/pull/476#issuecomment-594901438

**Comment by sophieliu15** [comment]
The first problem can be resolved by letting `ConfigReconciler` watch for changes in crds. I will address this problem after resolving the second problem (see below).

The cause of the second problem is that the controller manager's client's `RESTMapper` is initialized at startup and never updates when adding new CRDs to the apiserver. Therefore, the client is only aware of CRDs installed before starting the controller manager. This issue was address in [kubernetes-sigs/controller-runtime#321](https://github.com/kubernetes-sigs/controller-runtime/issues/321) and was fixed in [kubernetes-sigs/controller-runtime#544](https://github.com/kubernetes-sigs/controller-runtime/pull/554). However, after updating `controller-runtime` from current version (v0.2.2) to the latest version (v0.5.0), the object reconciler could be created successfully even when the CRD is not installed. It then received an error complaining the CRD was not found when the `Reconcile` method was called. I haven't found a way to check CRD before creating the reconciler or figured out the reason why the reconciler creation could succeed after the update. See discussion about this issue in kubernetes-sigs/controller-runtime#840. Working code can be found [here](https://github.com/kubernetes-sigs/multi-tenancy/compare/master...sophieliu15:crd_issue?expand=1).

**Comment by sophieliu15** [comment]
Add @adrianludwin and @yiqigao217 in the loop.

**Comment by adrianludwin** [comment]
Nice digging! If controller-runtime doesn't reject it, we'll just have to use the Discovery API to figure out if a type exists ourselves before we create the object reconciler. I have no idea how to do that but I suspect it's not _too_ terribly difficult.

**Comment by sophieliu15** [comment]
From discussion in kubernetes-sigs/controller-runtime#840 following are expected when a GVK does not exist after upgrading to controller-runtime v0.5.0:
- controller can be created successfully
- controller and manager will both terminate


We will have 3 PRs to address this issue:
- Upgrade controller-runtime to v.0.5.0: #504 
- Validate GVK before creating object reconciler
- Let config reconciler water custom resources
