### ISSUE TITLE
HNC: Refactor/split the EX map

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#495]
Refactor/split the EX map for 1) reconciler exclusion and 2) self-serve not allowed purposes. Currently, it serves both, but the namespace list could be different for the two purposes.

**Comment by adrianludwin** [comment]
Hey Yiqi, is this still a concern? Is it something that @adrianchung could help with?

**Comment by yiqigao217** [comment]
Yes, this should be good one!

**Comment by adrianludwin** [comment]
We're revisiting these issues in #374 but I don't think this one's too important. I'll remove the lifecycle label.
