### ISSUE TITLE
Baseline security profile today in a soft multitenant cluster

### ISSUE THREAD

**Issue by tashimi** [kubernetes-sigs/multi-tenancy#5]
### Baseline security profile today in a soft multitenant cluster

Using the current release of Kubernetes, assuming a Kubernetes cluster is shared between multiple teams (i.e. soft multitenancy), document how to configure a cluster for soft multitenancy.  

- N tenants per cluster, 1 Kubernetes namespace per tenant, no changes to Kubernetes upstream other than configuration
- See @easeway's KEP for some good concrete policies towards the end of the doc https://docs.google.com/document/d/1lFiRNDWgyoZWQfvQV2UYsH80CKW90jwSeBzWyssTf7g/edit#heading=h.xgjl2srtytjt

**Comment by teq0** [comment]
@easeway what are you thinking is the way forward here? It looks like your original KEP didn't get migrated to the new location, or did you split it up as per some of the PR conversation?

**Comment by easeway** [comment]
The original KEPs are out-of-date and I don't think we should continue on these. If nobody is going to take this task, I will probably write up an initial draft of baseline security profile proposal based on the _default_ security profile I proposed in the KEP and the [design](https://drive.google.com/open?id=1lFiRNDWgyoZWQfvQV2UYsH80CKW90jwSeBzWyssTf7g)

**Comment by srampal** [comment]
Let me take a crack at getting something going here.

**Comment by srampal** [comment]
Merged initial PR for this.

https://github.com/kubernetes-sigs/multi-tenancy/pull/21

Further PRs to come pending additional doc updates and feedback.
