### ISSUE TITLE
HNC : New repository

### ISSUE THREAD

**Issue by iam-merlin** [kubernetes-sigs/multi-tenancy#53]
hi @adrianludwin ,

The Hierarchical Namespace Controller is pretty interesting. Even if this project is a pre-alpha and also an incubation of the SIGs multi-tenancy... I think hnc is a project on its own (but it's a point of view).

I wonder if we can have a new repository for the HNC to simplify contribution and issue reporting?

**Comment by adrianludwin** [comment]
Thanks! I don't have a strong opinion myself but I'm fairly new to navigating the rules around SIGs, WGs and repos. Perhaps @tashimi or @srampal could comment? I do want this to remain under the MTWG, at least for now.

**Comment by tashimi** [comment]
I have no opinion on this. We opened up the multi-tenancy repo as a way to easily highlight all the multi-tenancy work going on, and I think that still holds true for this project. @iam-merlin I would suggest you just file issues here for now

**Comment by srampal** [comment]
@iam-merlin The current plan is to incubate this a bit more within the current repo. We agree that the work seems generic enough to have value beyond the multitenancy working group and will certainly promote it that way. However for now, it is most directly relevant to this area hence for now we are keeping it here until we discuss with other community leads on how/ where to take this forward. Please go ahead and file issues here for now. (Btw this is also the approach we are taking for other similar work such as the virtual clusters work from Alibaba.)

**Comment by adrianludwin** [comment]
Ok I'd recommend closing this issue for now (I don't have the permission to do so). We can revisit later this year.

**Comment by iam-merlin** [comment]
Thx everyone for the feedback 👍 

May I suggest a dedicated branch for PR?

**Comment by adrianludwin** [comment]
What's the benefit of a dedicated PR branch - just to keep the history
clean?

**Comment by iam-merlin** [comment]
Yep +1
