### ISSUE TITLE
MTB: Tenant without kubeconfig (SaaS provider multi-tenancy)

### ISSUE THREAD

**Issue by longngn** [kubernetes-sigs/multi-tenancy#533]
https://cloud.google.com/kubernetes-engine/docs/concepts/multitenancy-overview#saas_provider_multi-tenancy
SaaS provider multi-tenancy is a multi-tenancy use case where Kubernetes control plane is hidden from end-users (i.e. tenants). These tenants don't have access to control plane so we only need to run a subset of tests on their namespaces to verify PodSecurityPolicy, NetworkPolicy, ResouceQuota, etc.

**Comment by ShadowJonathan** [comment]
Does this fall within the scope of the Multi-tenancy kubernetes sig, though? Or would it be more interesting to build a platform on top of kubernetes that consumes it's api instead? Does this fall within the scope of kubernetes specifically?

**Comment by phoenixking25** [comment]
@JimBugwadia not relevant anymore
