### ISSUE TITLE
MTB: Dependency-inject config file

### ISSUE THREAD

**Issue by longngn** [kubernetes-sigs/multi-tenancy#534]
Currently the config file is read from [a static path](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/e2e/config/config.go#L7). We should let user inject it through commandline arg to improve flexibility and to ease adoption. This is especially useful for automating  running test, e.g. users can define config in a ConfigMap and then mount it in a pod for running tests.

Example command:

```shell
./tests.test --config path/to/config/file
```

**Comment by phoenixking25** [comment]
@JimBugwadia not relevant
