### ISSUE TITLE
MTB: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by phoenixking25** [kubernetes-sigs/multi-tenancy#535]
While running test packages, in case of unqualified tenant it leads to the panic error in the logs which doesn't make any sense actually. It should be handled with a meaningful error handler function and a log. https://github.com/kubernetes-sigs/multi-tenancy/blob/f08fc4cef21e8b0195cb9eda22c63804b2f76f84/benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go#L52

/assign @phoenixking25

**Comment by SomtochiAma** [comment]
Hello @phoenixking25, still working on this?

**Comment by phoenixking25** [comment]
@SomtochiAma yep

**Comment by phoenixking25** [comment]
Closing this issue, as whole code-base changed. Not facing this issue now.
