### ISSUE TITLE
Multi-Tenancy Benchmarks (MTB) Project

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/multi-tenancy#551]
This issue provides a description of the proposed GSoC Multi-Tenancy Benchmark Project.

The Kubernetes Multi-Tenancy Working Group is chartered with exploring and defining multi-tenancy models for Kubernetes. An overview of working group activities can be found in this Kubernetes Multi-Tenancy Working Group . 

The Multi-Tenancy Benchmarks effort focuses on measuring and validating the desired behaviors for multi tenancy. Part of this effort is to automate behavioral and configuration checks on existing clusters, which will be the focus of this project. This automated test suit will help all Kubernetes users validate whether their clusters are setup correctly for multi-tenancy.

The goals of the project will be to:
1. Help complete definitions of profile levels and associated tests. As part of this we will explore collaboration with the existing CIS benchmarks and profile levels.
2. Automate a e2e test suite that can be run once, or periodically, for a cluster
3. Generate a report for cluster administrators detailing an multi-tenancy violations and recommend actions for remediation. Potentially this could be integrated with the Dashboard.

Also see: 
* https://docs.google.com/document/d/1OuMwRdQbUQi02G7j4jyvscbv-6Mfa0VWjP2U_ghngHg/edit
* https://github.com/cncf/soc#kubernetes-multitenancy-working-group-benchmarks

**Comment by tangwz** [comment]
@JimBugwadia I would like to work this summer on this project. May I know how to start it.

**Comment by Dhiraj240** [comment]
@JimBugwadia  I have applied on community bridge and messaged you on slack for more information. You can check my portfolio here at https://dhiraj240.github.io/
