### ISSUE TITLE
HNC: Fix flaky test on changing the namespace annotation

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#560]
Part of #457 

In`hierarchical_namespace_test.go` to test the case of 'Conflict', we want to change the owned namespace's owner annotation to trigger the 'Conflict' state. Most of the times, the tests will pass. However, sometimes it may fail because it was not able to change the namespace annotation.

The error I got is:
Operation cannot be fulfilled on hierarchyconfigurations.hnc.x-k8s.io "hierarchy": the object has been modified; please apply your changes to the latest version and try again

**Comment by adrianludwin** [comment]
Can you retry it in a loop? This can happen if two clients try to update
the same object in succession too quickly.

**Comment by yiqigao217** [comment]
Do you mean put it in `Eventually()` instead of `Expect()`? It's using `Eventually()` now and it got timed out with the above error. I put a 1-second sleep for now.

**Comment by adrianludwin** [comment]
Eventually _should_ be a good enough loop, as long as we're passing in a
function that can get retried and not a value (we've been bitten by that
one before).

**Comment by yiqigao217** [comment]
This may not apply to this case since in `Eventually()` it will keep retrying to update and this won't help since the failure is from trying too much. The temporary work around I put is sleep 1 second for now before we get better solution.

Just referencing the [`Eventually()` func](https://github.com/kubernetes-sigs/multi-tenancy/blob/0e08fae14e5d1b664fe6a43855ff2eb4996208f6/incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go#L150) here in this issue.

**Comment by adrianludwin** [comment]
Odd. I thought Eventually() had a backoff?

**Comment by yiqigao217** [comment]
By backoff, do you mean it will not retry immediately after the previous attempt fails?

**Comment by adrianludwin** [comment]
> By backoff, do you mean it will not retry immediately after the previous attempt fails?

Yes, exactly. I thought it would have a short `time.Sleep` or something, but I don't really know.

**Comment by yiqigao217** [comment]
@adrianludwin can you please put this into v0.3 too? I believe the flaky test still exists.

**Comment by adrianludwin** [comment]
Let's see if I can get the bot to work.

/milestone hnc-v0.3

**Comment by adrianludwin** [comment]
Maybe it doesn't like that particular milestone?

/milestone hnc-backlog
