### ISSUE TITLE
HNC: delete objects created via makeObject after each test case.

### ISSUE THREAD

**Issue by sophieliu15** [kubernetes-sigs/multi-tenancy#586]
Right now objects created via [makeObject](https://github.com/kubernetes-sigs/multi-tenancy/blob/a2aaadbde836d60cd8c5aceead6679ecc6599a37/incubator/hnc/pkg/reconcilers/test_helpers_test.go#L153) are kept on the apiserver. We should find a way to delete objects after each test case so the objects created in one test case will not affect another test case (e.g., when computing NumSourceObjects).

**Comment by adrianludwin** [comment]
This might be a good one for @adrianchung

**Comment by sophieliu15** [comment]
Cool! @adrianchung I will leave the issue to you for now. Feel free to let me know if you need any more context or help about the issue!

**Comment by adrianchung** [comment]
Thanks! I will pick this up

**Comment by sophieliu15** [comment]
/close

This is fixed in #599
