### ISSUE TITLE
HNC: Rename release binary from kubectl-hierarchical_namespaces to kubectl-hns

### ISSUE THREAD

**Issue by adrianchung** [kubernetes-sigs/multi-tenancy#594]
Our released HNC binaries (for example, [v0.2.0](https://github.com/kubernetes-sigs/multi-tenancy/releases/tag/hnc-v0.2.0)) are currently named kubectl-hierarchical_namespaces. We should rename it to kubectl-hns to make it easier to spell and type.

**Comment by rjbez17** [comment]
We had a long discussion about this previously and I we decided to use a long name and recommend people use a symlink or alias to improve their lives. We felt that making the binary more obvious what it is was more important. kubectl-hns is not really that obvious to those unfamiliar.

@adrianludwin any thoughts?

**Comment by adrianludwin** [comment]
I discussed this with (other)Adrian, and the thing that I think is changing my mind is documentation.  If the "official" one is hierarchical-namespaces, that's what we should be documenting, right? But whenever we write a doc, I just want to type `kubectl hns`, and I think it's weird if you have to jump through a bunch of separate hoops to get that experience.

wdyt?

**Comment by rjbez17** [comment]
I'm fine with that, I was originally in the `kubectl-hns` boat the first time around :)

**Comment by rjbez17** [comment]
@adrianludwin do we want to target this for the next release?

**Comment by adrianludwin** [comment]
I think so - we're hoping that v0.3 will be an MVP. adrianchung@ can have this done in about 5min (he's a new Googler working on HNC)

**Comment by adrianludwin** [comment]
I'm _thinking_ v0.3 will go out next Friday or so
