### ISSUE TITLE
HNC: Add recommended RBAC rules in README

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#596]
For rules like 'don't change/delete hc instances', instead of implementing them in webhooks, we can just ask users to use RBAC rules to enforce them.

**Comment by yiqigao217** [comment]
I don't really find a good place to put this specific RBAC rules in the README. I think it may be okay not to add it since user are not likely to add a permission on `hierarchyconfigurations` any way? WDYT @adrianludwin ?

**Comment by adrianludwin** [comment]
If user's don't give permission to `hierarchyconfigurations`, then no-one can use them :)

Maybe add the documentation somewhere in here? 
https://docs.google.com/document/d/1R4rwTweYBWYDTC9UC-qThaMkPk8gtflr_ycHOOqzBQE/edit#heading=h.fbb92511bj1z

**Comment by adrianludwin** [comment]
Just left a footnote here: https://docs.google.com/document/d/1R4rwTweYBWYDTC9UC-qThaMkPk8gtflr_ycHOOqzBQE/edit?disco=AAAAGZZ-WLI. Do you think this is good enough?

**Comment by yiqigao217** [comment]
Thanks for the explanation and the update on the doc!
