### ISSUE TITLE
Give security researchers a secured multitenant cluster to work against

### ISSUE THREAD

**Issue by tashimi** [kubernetes-sigs/multi-tenancy#6]
### Give security researchers a reference cluster to work against. 

- We will use the results of #5 to give security researchers a reference cluster they can work against. No one working on the Kubernetes’ bug bounty had time to work on that configuration, so it would benefit the project if the work coming out of this group could be used and formally made part of the Kubernetes bug bounty project.
- Having a concrete reference architecture that a researcher could bring up and test against a defined threat model would make their job and our job of assessing the vulnerability easier.
- The m10 wg can then use their findings to improve our own work

**Comment by JayBeale** [comment]
I'm interested in providing this.

**Comment by tashimi** [comment]
@JayBeale did you still want to work on this? We have a couple proposals in the repo, they could use some more attention for sure tho

**Comment by sunstonesecure-robert** [comment]
did this ever go anywhere @JayBeale ?
