### ISSUE TITLE
HNC: CannotUpdate conditions might not be cleared in descendants when a hierarchy changes

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#605]
See https://github.com/kubernetes-sigs/multi-tenancy/pull/597#discussion_r403301854

**Comment by adrianludwin** [comment]
Also consider improving comments based on the linked discussion above.

**Comment by adrianludwin** [comment]
/cc @yiqigao217 

LMK if you're able to take this one on when your current PRs are finished

**Comment by yiqigao217** [comment]
Yes I will take this one. /assign @yiqigao217

**Comment by yiqigao217** [comment]
Sure, i will take this one.
/assign @yiqigao217

**Comment by yiqigao217** [comment]
Hi, @adrianludwin I was trying to introduce the `CannotUpdate` condition in my manual test. Is it the only way is to put a finalizer on the source object? Even for that, I seemed not able to add finalizers to an object manually by  e.g. `kubectl edit configmap`

**Comment by adrianludwin** [comment]
/reopen

#617 was just the test
