### ISSUE TITLE
HNC: Revisit if we need to write namespace when it's deleting

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#635]
See [comments](https://github.com/kubernetes-sigs/multi-tenancy/pull/624#discussion_r405189452) on #624 .

The tree labels could get updated before the namespace was eventually purged. We need to revisit this to see if it's necessary or how dangerous it could be for a not-up-to-date tree labels when the namespace is being deleted.

**Comment by adrianludwin** [comment]
I don't think we need to revisit this, removing lifecycle label.
