### ISSUE TITLE
Ability to specify Resource Quota at TenantAdmin Level

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/multi-tenancy#664]
There should be a way to specify the Total Resource Quota like below for all the tenant namespaces which are controlled by the Tenant and TenantAdmin Namespace.
This should include the below list :
- Total CPU
- Total Memory
- Maximum number of Pods

**Comment by ShadowJonathan** [comment]
Imo this is useful, @sb1975 is this stale?

**Comment by sb1975** [comment]
I guess so, wg-multitenancy towards stale I guess..
