### ISSUE TITLE
Tenant Operator does not work using the Readme

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/multi-tenancy#67]
It does not work, the t1adminnamespace or the t1-ns1 doesnot get created.

> root@wg-multitenancy:~#  kubectl apply -f multi-tenancy/tenant/config/crds/tenancy_v1alpha1_tenant

> tenancy_v1alpha1_tenantnamespace.yaml  tenancy_v1alpha1_tenant.yaml

> root@wg-multitenancy:~#  kubectl apply -f multi-tenancy/tenant/config/crds/tenancy_v1alpha1_tenant.yaml

customresourcedefinition.apiextensions.k8s.io/tenants.tenancy.x-k8s.io created

> root@wg-multitenancy:~#  kubectl apply -f multi-tenancy/tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml

customresourcedefinition.apiextensions.k8s.io/tenantnamespaces.tenancy.x-k8s.io created
root@wg-multitenancy:~# kubectl apply -f multi-tenancy/tenant/config/manager/
all_in_one.yaml  manager.yaml

> root@wg-multitenancy:~# kubectl apply -f multi-tenancy/tenant/config/manager/all_in_one.yaml

namespace/tenant-system created
clusterrole.rbac.authorization.k8s.io/manager-role created
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding created
validatingwebhookconfiguration.admissionregistration.k8s.io/tenant-validating-webhook-cfg created
service/controller-manager-service created
secret/webhook-server-secret created
statefulset.apps/controller-manager created

> root@wg-multitenancy:~# kubectl get crd

NAME                                CREATED AT
tenantnamespaces.tenancy.x-k8s.io   2019-09-20T21:54:48Z
tenants.tenancy.x-k8s.io            2019-09-20T21:54:42Z
root@wg-multitenancy:~#
root@wg-multitenancy:~# kubectl get statefulset
No resources found in default namespace.
root@wg-multitenancy:~# kubectl get statefulset -n tenant-system
NAME                 READY   AGE
controller-manager   1/1     25s

> root@wg-multitenancy:~# kubectl apply -f multi-tenancy/tenant/config/samples/tenancy_v1alpha1_tenant

tenancy_v1alpha1_tenantnamespace.yaml  tenancy_v1alpha1_tenant.yaml

> root@wg-multitenancy:~# kubectl apply -f multi-tenancy/tenant/config/samples/tenancy_v1alpha1_tenant.yaml

tenant.tenancy.x-k8s.io/tenant-sample created

root@wg-multitenancy:~# kubectl get tenant
NAME            AGE
tenant-sample   6s

> root@wg-multitenancy:~# kubectl get ns

NAME              STATUS   AGE
default           Active   3m44s
kube-node-lease   Active   3m47s
kube-public       Active   3m47s
kube-system       Active   3m47s
tenant-system     Active   61s

> root@wg-multitenancy:~# kubectl apply -f multi-tenancy/tenant/config/samples/tenancy_v1alpha1_tenantnamespace.yaml

Error from server (NotFound): error when creating "multi-tenancy/tenant/config/samples/tenancy_v1alpha1_tenantnamespace.yaml": namespaces "tenant1admin" not found

> root@wg-multitenancy:~# kubectl get ns

NAME              STATUS   AGE
default           Active   4m20s
kube-node-lease   Active   4m23s
kube-public       Active   4m23s
kube-system       Active   4m23s
tenant-system     Active   97s

> 

also directly using the link does not work, I need to git clone and then use it..
kubectl apply -f https://github.com/kubernetes-sigs/multi-tenancy/blob/master/tenant/config/crds/tenancy_v1alpha1_tenant.yaml
error: error parsing https://github.com/kubernetes-sigs/multi-tenancy/blob/master/tenant/config/crds/tenancy_v1alpha1_tenant.yaml: error converting YAML to JSON: yaml: line 618: mapping values are not allowed in this context

**Comment by Fei-Guo** [comment]
Can you post your controller log here? Thanks

**Comment by sb1975** [comment]
root@ubuntu:~/multi-tenancy# kubectl logs controller-manager-0 -n tenant-system
{"level":"info","ts":1569379512.5008686,"logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":1569379512.5011148,"logger":"entrypoint","msg":"setting up manager"}
{"level":"info","ts":1569379512.8101914,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1569379512.8102584,"logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":1569379512.810654,"logger":"entrypoint","msg":"Setting up controller"}
{"level":"info","ts":1569379512.8109324,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"tenant-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1569379512.8112457,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"tenant-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1569379512.8114936,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"tenantnamespace-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1569379512.8116634,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"tenantnamespace-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1569379512.8116887,"logger":"entrypoint","msg":"setting up webhooks"}
{"level":"info","ts":1569379512.8118513,"logger":"entrypoint","msg":"Starting the Cmd."}
E0925 02:45:12.904378       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.TenantNamespace: tenantnamespaces.tenancy.x-k8s.io is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "tenantnamespaces" in API group "tenancy.x-k8s.io" at the cluster scope
E0925 02:45:12.904538       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.Tenant: tenants.tenancy.x-k8s.io is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "tenants" in API group "tenancy.x-k8s.io" at the cluster scope
E0925 02:45:12.904378       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E0925 02:45:13.909602       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.TenantNamespace: tenantnamespaces.tenancy.x-k8s.io is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "tenantnamespaces" in API group "tenancy.x-k8s.io" at the cluster scope
E0925 02:47:36.202055       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "namespaces" in API group "" at the cluster scope
E0925 02:47:37.200781       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.Tenant: tenants.tenancy.x-k8s.io is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "tenants" in API group "tenancy.x-k8s.io" at the cluster scope
E0925 02:47:37.204032       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.TenantNamespace: tenantnamespaces.tenancy.x-k8s.io is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "tenantnamespaces" in API group "tenancy.x-k8s.io" at the cluster scope
E0925 02:47:37.204495       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:tenant-system:default" cannot list resource "namespaces" in API group "" at the cluster scope

**Comment by Fei-Guo** [comment]
You may manually apply the fix and it should work. Thanks for catching this.

**Comment by sb1975** [comment]
But whats the fix please, can you please specify that ?

**Comment by sb1975** [comment]
ok so I installed docker,go,kind and then followed the steps. it all worked as expected. :)
