### ISSUE TITLE
Duplicate Code in https://github.com/kubernetes-sigs/multi-tenancy/blob/master/tenant/config/manager/all_in_one.yaml

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/multi-tenancy#671]
It seems line 15-23 in this code : https://github.com/kubernetes-sigs/multi-tenancy/blob/master/tenant/config/manager/all_in_one.yaml
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create

This is exactly same as in lines 59-67.
Can someone clarify the difference, otherwise one of it can be deleted.

**Comment by Fei-Guo** [comment]
Feel free to create a PR to fix it. Thanks
