### ISSUE TITLE
Support for Aggregate quota resources for all namespaces of a tenant

### ISSUE THREAD

**Issue by singhannie** [kubernetes-sigs/multi-tenancy#690]
Aggregate of resource quotas for all namespaces for a tenant shall remain below Maximum aggregated resource quotas, which might associated with tenant CR in some way. Given that workloads of a tenant would share the resource of the same Kubernetes cluster with other tenants, and the tenant admin has ability to create new namespaces and associate resource quotas to it, maximum aggregated resource quotas would provide a safeguard against resource starvation of of workloads for other tenants.

Maximum aggregated resource quotas will be required to be defined for following compute and storage quotas (this is just for example, list can certainly grow):
1- maximum number of cpus across all namespaces for a tenant.
2- maximum size of memory across all namespaces for a tenant.
3- maximum size of storage for a given storage class across all namespaces for a tenant.
4- maximum size ephemeral storage across all namespaces for a tenant.

**Comment by sb1975** [comment]
I think the Aggregate Resource Quota can be enforced at TenantAdmin Level.
Could this be enforced by using the HNC (https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc ) ? or any other mechanism ?

**Comment by adrianludwin** [comment]
HNC doesn't directly support hierarchical resource quota, though there was an IBM team working on implementing a type of RQ that supported HNC. There's no reason someone couldn't build it, it's just not a priority for our usecases right now, but we'd be happy to accept contributions.

**Comment by sb1975** [comment]
@adrianludwin , do you mind adding reference to the code or issue here, in case it exists , thanks.

**Comment by adrianludwin** [comment]
It was the first agenda item on Dec 3 2019: https://youtu.be/V0Zw82nOAEE

**Comment by sb1975** [comment]
This issue relates to https://github.com/kubernetes-sigs/multi-tenancy/issues/664
