### ISSUE TITLE
[VC]: Can't run go generate, GOPATH issues.

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/multi-tenancy#713]
### Background:
I'm using `direnv` so I have the environment set up properly with the `GOPATH` from the root of `multi-tenancy` and the tools directory. I believe there is something wrong with the way we have our dependencies packaged where a clean install doesn't install a supported `k8s.io/code-generator`.

```
→ make generate
go generate ./pkg/... ./cmd/...
W0512 15:16:46.494634    9842 parse.go:242] Ignoring child directory tenancy: unable to import "tenancy": go/build: importGo tenancy: exit status 1
can't load package: package tenancy: malformed module path "tenancy": missing dot in first path element

W0512 15:16:46.676141    9842 parse.go:242] Ignoring child directory tenancy/v1alpha1: unable to import "tenancy/v1alpha1": go/build: importGo tenancy/v1alpha1: exit status 1
can't load package: package tenancy/v1alpha1: malformed module path "tenancy/v1alpha1": missing dot in first path element
```

@Fei-Guo is there a specific version you have installed? This isn't managed right now through `go mods`…

**Comment by zhuangqh** [comment]
have you done `go mod download`?

**Comment by christopherhein** [comment]
I have, it didn't change anything. Are you using `direnv` and having it set based on what is in `/multi-tenancy/.envrc`?

**Comment by christopherhein** [comment]
/close

Apparently I wasn't supposed to use `direnv` and it's configuring my env wrong. `direnv deny` from the root of the `/multi-tenancy` repo and retrying seems to solve this.
