### ISSUE TITLE
[VC]: Manifest Regeneration Removing shortNames

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/multi-tenancy#714]
I run `make manifest` it regenerates the crds and also removes the `shortNames` from them.

I am using the `controller-gen@0.1.1` like it is documented in the `Makefile` and since there isn’t any `shortName` `controller-gen` markers in the `*_types.go` files I end up with a `diff` like:

```
→ git diff
diff --git a/incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml b/incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
index 36506d31..e5d1e16f 100644
--- a/incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
+++ b/incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
@@ -10,8 +10,6 @@ spec:
   names:
     kind: ClusterVersion
     plural: clusterversions
-    shortNames:
-    - cv
   scope: Cluster
   validation:
     openAPIV3Schema:
diff --git a/incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml b/incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
index de52e2a7..96a2adcf 100644
--- a/incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
+++ b/incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
@@ -10,8 +10,6 @@ spec:
   names:
     kind: Virtualcluster
     plural: virtualclusters
-    shortNames:
-    - vc
   scope: Namespaced
   validation:
     openAPIV3Schema:
```

Is this expected? Am I running the wrong version of `controller-gen`? Should we update to a later version of `controller-gen` in the `Makefile` and add `// +kubebuilder:resource:shortName=...`?

**Comment by charleszheng44** [comment]
Hi Chris,

Yes, this is expected. We use kubebuilder v1.0.8 to build the scaffolding code for VC. I think kubebuilder begun to support `shortName` since v2. I used to add the `shortName` manually.  

If you can update the controller-gen and make the `shortName` work, that would be great :)

**Comment by christopherhein** [comment]
Awesome, thanks @charleszheng44. Happy to look into doing that. I found this while solving for #707 so once I can finish the test suite for that I will start on this.
