### ISSUE TITLE
HNC: consider making leaf subnamespace deletion easier

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#716]
Right now, to delete a subnamespace, you first have to set `allowCascadingDelete` on the subnamespace itself (or its parent). This makes subnamespaces _harder_ to delete than regular namespaces, which have no such protection.

The goal of `allowCascadingDelete` was really to prevent _cascading_ deletions - that is, unintentionally deleting _multiple_ namespaces. I wonder if we could skip this check unless the namespace being deleted actually has subnamespaces itself. So for example, I could say:

```
k hns create sub -n parent
k delete subns sub -n parent
```

But not:
```
k hns create sub -n parent
k hns create subsub -n sub
k delete subns sub -n parent # fails because of subsub
```

**Comment by adrianludwin** [comment]
/assign @yiqigao217 

This is on the HNC backlog so it's not immediately urgent (e.g. it's not for v0.4)

**Comment by yiqigao217** [comment]
@adrianludwin WDYT if we also add webhook rules on denying delete namespace when it has children, since otherwise the children will be orphaned and they will have "parentMissing" condition, which is a condition that's easy to get since we dont have any webhook on that.

**Comment by rcolline** [comment]
Can we just treat all namespaces the same.  If you have namespace DELETE privilege on the namespace you can delete it.   

What is driving the need to treat HNC namespaces different?

**Comment by adrianludwin** [comment]
Discussed the rationale behind subnamespaces offline. We considered an
alternative where the "SubnamespaceAnchor" becomes vestigial after the
namespace is first created, and HNC create ClusterRoles and
ClusterRoleBindings for the newly created child namespace (basically
copying permissions from the SubnamespaceAnchor to the namespace). This
means that the namespace can then be deleted via `k delete ns child`
instead of `k delete subns child -n parent`. I hadn't considered this
before so it's an interesting decision to write down.

We agreed that this change isn't essential today (even if we agreed to make
it) and we'll watch for signs that we should switch to this kind of scheme
in the future.

**Comment by akessner** [comment]
> ubnamespaces offline. We considered an alternative where the "SubnamespaceAnchor" becomes vestigial after the namespace is first created, and HNC create ClusterRoles and ClusterRoleBindings for the newly created child namespace (basically copying permissions from the SubnamespaceAnchor to the namespace). This means that the namespace can then be deleted via `k delete ns child` instead of `k delete subns child -n parent`. I hadn't considered this before so it's an interesting decision to write down. We agreed that this change isn't essential today (even if we agreed to make it) and we'll watch for signs that we should switch to this kind of scheme in the future.
> […](#)

We are having trouble with ArgoCD removing namespaces.
Was this new approach ever used?
