### ISSUE TITLE
HNC: consider preventing orphans

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#717]
Currently, HNC lets you delete parents of full namespaces without any restrictions, e.g.:

```
k create ns parent
k create ns child
k hns set child -p parent
k delete ns parent # ok; `child` now has CritParentMissing
```

Since our admission webhooks stop you from creating most other critical conditions, I'm wondering if we should do the same thing here? E.g., maybe we should insist that all (full) children are removed from this tree _before_ allowing deletion? Or maybe it would need to integrate with `allowCascadingDelete` in some way (though this isn't really _cascading_ deletion so we may need a new name for it).

**Comment by adrianludwin** [comment]
/assign @yiqigao217 

Again this isn't for HNC v0.4

**Comment by yiqigao217** [comment]
/remove-lifecycle stale
@adrianludwin this can remain in backlog and not into v0.8 milestone.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/30

/close
