### ISSUE TITLE
HNC: allow us to uninstall easily without removing CRDs

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#718]
Right now, if you say `kubectl delete -f <hnc-version>/manifest.yaml`, _everything_ gets deleted, including the CRDs. It would be nice if we could delete the HNC namespace, deployment, webhooks etc but not the user data.

/good-first-issue

**Comment by Divya063** [comment]
@adrianludwin I would like to work on this.

**Comment by adrianludwin** [comment]
Hi @Divya063, thanks for the offer! Do you have experience with kustomize, and some idea about how we'd do this? I think we somehow want to have an "uninstall" manifest, so you could say `kubectl delete -f <hnc-version>/safe-uninstall.yaml`, where `safe-uninstall.yaml` has everything that `manifest.yaml` does _except_ the CRDs. The build process will also need to be updated.

Do you know how to do all this? Thanks!

**Comment by adrianludwin** [comment]
See #824 for an interesting inversion of this bug.

**Comment by adrianludwin** [comment]
This is somewhat addressed by #839 so I think we can push this to the backlog.

**Comment by adrianludwin** [comment]
Replaced by #1320
