### ISSUE TITLE
[VC]: Renaming Virtualcluster -> VirtualCluster?

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/multi-tenancy#728]
What do you think about changing the capitalization of the `Virtualcluster` to follow `ClusterVersion` and common patterns in other Kubernetes projects to `VirtualCluster`?

**Comment by christopherhein** [comment]
@Fei-Guo @resouer @zhuangqh wdyt?

**Comment by Fei-Guo** [comment]
If there is no strong reason, i'd rather not change it now. We have users that already use vc crd in production. Changing the crd name will break the client. This does not mean we cannot change it thought if it is indeed an anti-pattern.

**Comment by christopherhein** [comment]
Sounds good, it seems like something we should do before v1beta1 would be all I’d like to see

**Comment by christopherhein** [comment]
That’s fair.

**Comment by ShadowJonathan** [comment]
Maybe put this on a milestone or a todo-list for a major version/development leap where clients already would need to update their configurations.

**Comment by Fei-Guo** [comment]
Yes, I added to my internal TODO list. The list will be posted publicly once the project graduates.

**Comment by christopherhein** [comment]
Thanks @Fei-Guo, by graduation, do you have something specific you are working towards, any issue I can read about what is left before then?
