### ISSUE TITLE
HNC: Complete security review for sub-project graduation

### ISSUE THREAD

**Issue by rjbez17** [kubernetes-sigs/multi-tenancy#749]
Complete an security review with approvals from at least one sig-auth technical lead as part of the graduation criteria to become a sub-project.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1687-hierarchical-namespaces-subproject/README.md#graduation-criteria

**Comment by mikedanese** [comment]
This is done.

/close

**Comment by sunstonesecure-robert** [comment]
was this review published somewhere?
