### ISSUE TITLE
HNC: Revisit the accuracy of the counter metrics

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#752]
Since there's a lot of changes on the reconcilers after the counter metrics is added, we may need to revisit this to ensure we don't miss any e.g. increment on the api read/write counter.

/assign @yiqigao217 
/cc @adrianludwin

**Comment by adrianludwin** [comment]
Good idea, though not critical for v0.4 since these metrics are mainly used for performance monitoring, not functionality.
