### ISSUE TITLE
HNC: add e2e tests acting-as different accounts

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#783]
Add a couple of end-to-end tests that make use of act-as features to prove that certain users can take actions that others can't. They don't need to be as comprehensive as the unit tests - just good enough to ensure that the auth system isn't completely broken on any one flavour of K8s (eg GKE, EKS, AKS, Kind, etc).

**Comment by mbtamuli** [comment]
Hey @adrianludwin, I would like to work on this issue.

Can you let me know where should I start?

Also, I can do the testing for Kind locally and I also have a GCP account with some credits remaining so I would be able to test there. What about EKS, AKS?

**Comment by adrianludwin** [comment]
Thanks for the offer, we appreciate it!

We don't currently have any testing on EKS/AKS so I'm afraid I can't help you there. However, if you make a test that can work on Kind - for example, by using service accounts instead of user accounts - then I'm pretty sure it will work anywhere, because K8s service accounts are identical on all flavours of K8s. So that's the way I'd recommend going.

The README has this note about testing with SAs:

> KIND doesn't integrate with any identity providers - that is, you can't add "sara@foo.com" as a "regular user." So you'll have to use service accounts and impersonate them to test things like RBAC rules. Use `kubectl --as system:serviceaccount:<namespace>:<sa-name>` to impersonate a service account from the command line, [as documented here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-subjects).

Does this give you enough to get started?
