### ISSUE TITLE
HNC: kubectl hns config set-type plugin seems not working

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#789]
When testing #761 , I found I cannot add additional type through kubectl plugin:

I tried `kubectl hns config set-type --apiVersion v1 --kind Secret propagate` to add additional `Secret` type to hncconfig besides `Role` and `RoleBinding` and it didn't show up in the `spec.types` when I looked it up later by `k get hncconfigurations.hnc.x-k8s.io -oyaml`. 

/assign @yiqigao217

**Comment by adrianludwin** [comment]
This worked for me just a few days ago. Do you have a recent version of the
plugin? Did you get any errors when you said `k hns config set-type` or did
it just *appear* to pass, but it later turned out it hadn't had any effect?

**Comment by yiqigao217** [comment]
Oh, I can see the added `Secret` in the `spec.types` now. Not sure why I didn't earlier. I can see it both in the master branch and my changed branch now.

I got nothing after `set-type` so it just *appear* to pass both before and now.
