### ISSUE TITLE
HNC: Investigate a test flake in hncconfig NumSourceObjects

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#823]
Find the failed test logs [here](https://gist.github.com/yiqigao217/f1bcabe76021bc3299dfede9e73397ff#file-hnc-822-test-flake-logs).

It failed in #822 prow test on line https://github.com/kubernetes-sigs/multi-tenancy/blob/hnc-v0.4/incubator/hnc/internal/reconcilers/hnc_config_test.go#L361 where it returns 2 instead of 1.

It was never flaky when I ran `make test` and it passed the retest. I think it's irrelevant to #822 and is just an error in the prow job, but still keep a record here in case it masks real rare issues.

**Comment by adrianludwin** [comment]
/assign @GinnyJI 

Will this be fixed by your upcoming PR? If so, just add it to the PR description (e.g. "Fixes #823"). Note that you _can't_ add that line to the Git commit message, _only_ to the PR description.

**Comment by adrianludwin** [comment]
I haven't seen many flakes here for a while.
/close
