### ISSUE TITLE
HNC: allow direct deletion of a subnamespace if its parent doesn't exist

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#847]
/assign @yiqigao217 

This comes up in some of the e2e tests - a namespace with the subnamespaceOf annotation exists, but its parent doesn't. We should allow it to be deleted.

**Comment by yiqigao217** [comment]
It seems that to delete this subnamespace, users (with delete ns permission) could just edit the ns to remove the `subnamespaceOf` annotation and then perform the ns deletion if they have update ns permission. Do we still need to have a webhook rule specific for this case? @adrianludwin

**Comment by adrianludwin** [comment]
Hmm. Here's the scenario that brought this up:

   - I created a bunch of subnamespaces
   - I uninstalled HNC, including all the CRDs. This means all the anchors
   were deleted, but the subnamespaceOf annotations were still present
   - I reinstalled HNC. Now I can't delete any of the namespaces without
   either editing them one-by-one, or recreating the anchors one-by-one.

I feel like this third step should be easier. Do you have any
other suggestions?

**Comment by yiqigao217** [comment]
Ah just had the same issue when running e2e test deleting CRD with @GinnyJI . Yes, right now the simplest way is to edit ns to remove the annotation. Sure, allowing direct deletion would be much easier. Will work on it next!
