### ISSUE TITLE
HNC: Add a presubmit to ensure `make generate` doesn't produce diffs

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#852]
In #841 , a change to the auto-generated manifest was not included (patched by #851 later). We should prevent this by adding a presubmit to make sure the `make generate` doesn't produce any diffs.

**Comment by adrianludwin** [comment]
Moved to https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/25

/close
