### ISSUE TITLE
HNC: Revisit the subnamespace deletion rule in namespace validator 

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#876]
See [discussions](https://github.com/kubernetes-sigs/multi-tenancy/pull/870#discussion_r452959296)

Since we changed (**loosen**) the restriction to not requiring `allowCascadingDelete` set to be able to delete a leaf subnamespace, we probably need to revisit the subnamespace deletion validation to make sure it's **strict** enough that there are no other namespaces being deleted that user may not aware of.

**Comment by adrianludwin** [comment]
Yeah, it used to be that the rule was, "don't let a subns be deleted unless it has aCD set," so it made sense to check all the children while deleting a parent. But now the rule is, "don't delete any namespace if it's not explicitly being deleted," so it doesn't make sense to allow a parent to be deleted even if someone previously set aCD on all its subnamespace children.

**Comment by adrianludwin** [comment]
/assign @GinnyJI 

This would be a nice simplification and cleanup.
