### ISSUE TITLE
HNC: Change singleton names from hier/Hierarchy to hierarchy/HierarchyConfiguration

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#88]
Currently, the HNC defines the hierarchy using a Kind called `Hierarchy` (kubectl short name: `hierarchy`/`hierarchies`) and a per-namespace singleton called `hier`. However, these names have a few problems:

- `hier` is hard to say and looks kind of dumb. I wanted it to be short so we could easily type it into kubectl, but the new kubectl plugin (`kubectl hnc`) makes this less relevant than I initially thought.
- `hierarchy` is a pretty generic name to reserve for the HNC in kubectl.

Here are the options I'm considering:

1. Singleton name `hierarchy`, Kind `HierarchyConfiguration`/`hierarchyconfig`/`hierarchyconfigs`
2. Singleton name `tree`, Kind `TreeConfiguration`/`treeconfig`/`treeconfigs`

Which would you prefer? Or do you have another preference?

**Update: we are going with option #&#x2060;1**

**Comment by rjbez17** [comment]
I don't have a strong preference but slightly towards #1.

**Comment by adrianludwin** [comment]
Thanks, I think I'm leaning towards option 1 as well if I don't hear any strong objections.

**Comment by tashimi** [comment]
That works! I like spelling out the full name. `hier` will just lead to `high-er` and `higher-archery`

**Comment by adrianludwin** [comment]
I need to remember hier-archery for a project name in the future. Ok, I'll
either start working on a PR or perhaps consider giving this to one of the
interns.

**Comment by tashimi** [comment]
Yes! Tag it good first issue and someone can pick it up!

**Comment by tashimi** [comment]
![tenor-50362273](https://user-images.githubusercontent.com/719646/66162058-76340100-e5e2-11e9-97f1-bba2065233da.gif)

**Comment by entro-pi** [comment]
I'd like this as my first issue!

**Comment by adrianludwin** [comment]
@entro-pi are you one of the Outreachy interns?

**Comment by entro-pi** [comment]
Yes I am one of them! I go by py-entro and Taylor elsewhere.

Cheers!

**Comment by adrianludwin** [comment]
Ok let me know when you're a [member of kubernetes-sigs](https://github.com/kubernetes-sigs/multi-tenancy#join-this-repo), or just assign this to yourself if you are already

**Comment by entro-pi** [comment]
Ok! To clarify, I am an Outreachy Applicant at this step. I'm on the
contribution step of the application process so I'm unsure if I get to be
added to kubernetes-sigs just yet.

As well, my pronouns are they/them.

Thank you!
Taylor

**Comment by adrianludwin** [comment]
re pronouns - noted, thanks! re sig - Tasha should be able to sponsor you, I think. I can't since I'm not a full member of this repo myself.

If it turns out that you can't actually be assigned the issue just let me know, I'll grab it myself but let you submit the PR.

**Comment by rjbez17** [comment]
I was actually going to suggest we go with a Archie theme.

**Comment by rjbez17** [comment]
My daughter closed her first open source issue I guess...sorry about that :)

**Comment by tashimi** [comment]
@rjbez17 it's good to start early!

@entro-pi you can become a member of kubernetes-sigs by filling out this form and following the checklist. Be sure to do @kubernetes-sigs, not @kubernetes for the form (or do both if you want) 
- docs: https://github.com/kubernetes/community/blob/master/community-membership.md
- form: https://github.com/kubernetes/org/issues/new?template=membership.md&title=REQUEST%3A%20New%20membership%20for%20%3Cyour-GH-handle%3E

**Comment by entro-pi** [comment]
Excellent! Thank you so much, I'll get to that tonight.

**Comment by adrianludwin** [comment]
Fixed via PR #98
