### ISSUE TITLE
HNC: CRD conversion for HNCConfig SynchronizationMode

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#885]
Part of #868 

In v1alpha2, we will change the modes from `propagate`, `remove`, `ignore` to `Propagate`, `Remove`, `Ignore` (camel case). A straightforward conversion is to convert the valid modes to the other version and keep invalid values as is. 

However, there are two scenarios that the simple mapping doesn't work when:
* A type has `Propagate` mode in v1alpha1 HNCConfig. Since the value is not recognized, the mode in status will be `ignore`. However, if you get the resource in v1alpha2, it will look confusing with `Propagate` in spec and `Ignore` in status.
* A type has `propagate` mode in v1alhpa2 HNCConfig, which shouldn't be recognized and should be treated as `Ignore` in status but now converted to a valid mode in v1alpha1, so the status for it is `propagate` (since v1alpha1 is the storage version). 

A simple solution could be that for the valid modes, no matter in lower case or camel case, they will all be converted to the other version. Then the above scenarios won't happen.

**Comment by adrianludwin** [comment]
Is it possible to have `propagate` in v1a2 if we set up the schemas correctly? I'm not sure if this is worth worrying about _too_ much.

I think it's fine to say that if our storage version is v1a1 and it contains the text `Propagate` (which is invalid in v1a1), when we convert that to v1a2 we could display it as something like `InvalidConvertedValuePropagate`.

**Comment by yiqigao217** [comment]
Update: We will not convert any unknown modes since we introduced the enum schema validation first #902 .

**Comment by adrianludwin** [comment]
@yiqigao217 is this complete?

**Comment by yiqigao217** [comment]
Fixed by #1026
