### ISSUE TITLE
HNC: Finalize the initial list of HNC-controlled objects

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#91]
Currently, the HNC will propagate `Roles`, `RoleBindings` and `Secrets`. I'd like to propose the following additional Kinds that get propagated in HNC 0.1:

- `ConfigMap`
- `NetworkPolicy`
- `PodSecurityPolicy`
- `ResourceQuota`
- `LimitRange`

That is, all the common policy objects that an admin might want to set and then forbid subadmins from modifying.

In HNC 0.2 (aka Phase 2 in the design doc), we can look at making this set configurable.

**Comment by adrianludwin** [comment]
/good-first-issue
/unassign

Let's go with the list shown above. This should be an easy PR for someone.

**Comment by entro-pi** [comment]
I'd like to take this on, I studied the problem during my downtime recently and think I have a good idea of how to solve it, or at least the questions I need to ask.

/assign @entro-pi

**Comment by entro-pi** [comment]
Here's a question, should I close this issue? (if I can)?

**Comment by adrianludwin** [comment]
Yup! If you can't, I will.

**Comment by entro-pi** [comment]
Fixed by #116

**Comment by entro-pi** [comment]
Looks like I can't, would you mind?
