### ISSUE TITLE
HNC: v0.6.0 release notes

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#916]
/cc @yiqigao217 

Can you help me populate this bug with anything we should mention in the v0.6 release notes? I know it's >1mo away but that just makes it more important to track recent changes before we forget them.

**Comment by adrianludwin** [comment]
Fixed #845

**Comment by yiqigao217** [comment]
Yes sure, so far I filed #907 about previous unknown HNCConfig unknown value will be validated by enum schema validation that admins must fix it before updating the config.

I will add later notes as comments here.

**Comment by adrianludwin** [comment]
Yeah maybe close #907 after updating whatever information you want to
include in this bug.

**Comment by yiqigao217** [comment]
Sure closing #907 now since that's all included in my previous comment.

**Comment by yiqigao217** [comment]
Adding a new one from discussion: Conditions in v1a1 will be caught in v1a2 as well. However, we may still add to the release note to suggest users making sure all resources are in good state before upgrading.

**Comment by yiqigao217** [comment]
Remember to mention we don't support 0.6 -> 0.5 downgrade! See [v1a2 design doc](http://bit.ly/hnc_v1alpha2).

**Comment by yiqigao217** [comment]
Just adding more:
1. Condition schema is changed; `Crit` conditions are changed to `ActivitiesHalted`; Object conditions are replaced by events; `namespaceConditions` field is merged into `conditions` field in HNCConfig
1. Enforced types `roles` and `rolebindings` are removed from HNCConfig spec
1. Sync modes are changed to camel case.

**Comment by adrianludwin** [comment]
Ok, draft release notes are up at https://github.com/kubernetes-sigs/multi-tenancy/releases/tag/hnc-v0.6.0-rc1. PTAL!
