### ISSUE TITLE
[MTB] change "-t" to "--as" to match kubectl

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/multi-tenancy#936]
To follow kubectl conventions, we should support "--as" and "--as-group" flags instead of "-t".

Also, in the examples it would be best to use a role-binding and a user name, instead of using service accounts.

We can also provide steps how to create a sample role-binding in the tenant namespace.

**Comment by phoenixking25** [comment]
resolved via https://github.com/kubernetes-sigs/multi-tenancy/pull/938
