### ISSUE TITLE
[MTB] Improve kubectl-mtb CLI UX 

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes-sigs/multi-tenancy#941]
Currently, we show a fairly cryptic error message:

```
➜  multi-tenancy git:(master) ✗ kubectl-mtb test
error: Please specify any resource
```

Instead we should show the user the (appropriate) command usage:

```
➜  multi-tenancy git:(master) ✗ kubectl-mtb get

Usage:
  kubectl-mtb get <resource> [flags]

Resources:
  benchmarks: multi-tenancy benchmarks

Global Flags:
  -c, --category string     Category of the benchmarks.
  -p, --profile-level int   ProfileLevel of the benchmarks. (default 3)
```

In the case above, we should show the user the available resources (we only have 1).

Another example of how we can show the usage:

```
➜  multi-tenancy git:(master) ✗ kubectl-mtb test benchmarks
error: user name is required

Usage:
  kubectl-mtb test [flags]

Flags:
      --as string          (required) user name to impersonate
  -h, --help               help for test
  -n, --namespace string   (required) tenant namespace
  -o, --out string         (optional) output reporters (default, policyreport) (default "default")
  -s, --skip string        (optional) benchmark IDs to skip

Global Flags:
  -c, --category string     Category of the benchmarks.
  -p, --profile-level int   ProfileLevel of the benchmarks. (default 3)

```

Also, lets add required / optional to each flag as a prefix as shown above.

**Comment by phoenixking25** [comment]
> Currently, we show a fairly cryptic error message:
> 
> ```
> ➜  multi-tenancy git:(master) ✗ kubectl-mtb test
> error: Please specify any resource
> ```
> 
> Instead we should show the user the (appropriate) command usage:
> 
> ```
> ➜  multi-tenancy git:(master) ✗ kubectl-mtb get
> 
> Usage:
>   kubectl-mtb get <resource> [flags]
> 
> Resources:
>   benchmarks: multi-tenancy benchmarks
> 
> Global Flags:
>   -c, --category string     Category of the benchmarks.
>   -p, --profile-level int   ProfileLevel of the benchmarks. (default 3)
> ```
> 
> In the case above, we should show the user the available resources (we only have 1).
> 
> Another example of how we can show the usage:
> 
> ```
> ➜  multi-tenancy git:(master) ✗ kubectl-mtb test benchmarks
> error: user name is required
> 
> Usage:
>   kubectl-mtb test [flags]
> 
> Flags:
>       --as string          (required) user name to impersonate
>   -h, --help               help for test
>   -n, --namespace string   (required) tenant namespace
>   -o, --out string         (optional) output reporters (default, policyreport) (default "default")
>   -s, --skip string        (optional) benchmark IDs to skip
> 
> Global Flags:
>   -c, --category string     Category of the benchmarks.
>   -p, --profile-level int   ProfileLevel of the benchmarks. (default 3)
> ```
> 
> Also, lets add required / optional to each flag as a prefix as shown above.

Should we use this type of output  format in this  case?

> phoenix@apo:~$ kubectl get
You must specify the type of resource to get. Use "kubectl api-resources" for a complete list of supported resources.

> error: Required resource not specified.
> Use "kubectl explain <resource>" for a detailed description of that resource (e.g. kubectl explain pods).
> See 'kubectl get -h' for help and examples

**Comment by JimBugwadia** [comment]
Yes, we can have a short sentence to be more precise with the error and then since our usage is not too long show the usage.

**Comment by phoenixking25** [comment]
I have changed to what you have proposed in the description
