### ISSUE TITLE
HNC: Remove v1alpha1 from CRD status.storedVersions

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#954]
Part of #868 

After all v1alpha1 CRs are gone in the cluster, we can remove v1alpha1 from CRD `status.storedVersions` so that we can eventually remove v1alpha1 from the CRD `spec.versions`.

I tested manually after the conversion #953 by `kubectl edit crd XXX` and deleting the v1alpha1 listed under `status.storedVersions`. The v1alpha1 was added back immediately. It shouldn't be the case if the reconcilers only read and write in v1alpha2 that should overwrite the v1alpha1 resources. After investigation, it seems that we cannot remove it manually by `kubectl` - see issue https://github.com/kubernetes/website/issues/18248 . We will have to test it by golang script.

Anyway, this change is needed. We can have it as the 2nd PR for the API transition.

**Comment by adrianludwin** [comment]
That's... annoying... that you can't remove it via kubectl. However, with that said, we were planning on automating it anyway so the golang solution works for us!

**Comment by yiqigao217** [comment]
> That's... annoying... that you can't remove it via kubectl. However, with that said, we were planning on automating it anyway so the golang solution works for us!

Agreed!
