### ISSUE TITLE
HNC: subnamespaces sometimes deleted if CRD is removed too quickly after installation

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#972]
There seem to be some cases where HNC doesn't notice that the CRD is being deleted, so it thinks that the anchors being deleted means that the user wants to delete the subnamespaces as well. This is clearly wrong.

I never see this problem in our e2e tests, but I've seen some problems with GKE Hierarchy Controller where if I enabled and disable it quickly, we get this problem. I'm _guessing_ that there's something about installing HNC and quickly removing it that has some weird interaction with the controller-runtime object cache.

<strike>The first thing will be to confirm that we're using a [delegating client](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#DelegatingClient) as I suspect, and if so, change it to a regular (uncached) client.</strike> Since we are using the [default client](https://github.com/kubernetes-sigs/multi-tenancy/blob/5d64462ab0a0c0825bb8d98855c296621ec28a73/incubator/hnc/internal/reconcilers/setup.go#L27), this means we're currently getting a [delegated client](https://github.com/kubernetes-sigs/controller-runtime/blob/21a81bced73737f6bbc7c2a973d17c55c505e91c/pkg/manager/manager.go#L202) which caches reads from the apiserver, which is probably why we're not seeing that the CRDs have been deleted.

**Comment by adrianludwin** [comment]
I saw this happen on 2/5 trials without any artificial delays. When I added a 30s sleep between creating the subns and deleting the CRD, I got 0/5 errors. Not definitive, but it does suggest that a delay helps, and explains why we've never seen this on our e2e tests before (which all have HNC in a fairly stable state before running). It should be fairly easy to delete the pods to recreate this in the e2e tests.

**Comment by adrianludwin** [comment]
I got 1/5 errors with a 15s sleep.

**Comment by adrianludwin** [comment]
I wonder if this was fixed by #1305

**Comment by yiqigao217** [comment]
Tested deleting and reapplying CRD quickly multiple times and didn't see subnamespace got deleted.

/close
