### ISSUE TITLE
HNC: Question about some limitations of HNC

### ISSUE THREAD

**Issue by tcnksm** [kubernetes-sigs/multi-tenancy#973]
Currently, I'm working on the system which is based on the HNC. While working on it, I started to wonder about the limitation of HNC. I went through the guide and design doc but I could not find them. The followings are what I want to confirm:

- How many levels can we nest the namespaces?
- How many child namespaces one parent can hold?

If I miss the doc, please redirect me! Thanks.

**Comment by adrianludwin** [comment]
Hi @tcnksm , thanks for this question and you're right, we need to update the documentation.

There are no hard-coded limitations in HNC: any namespace can have any number of children, and there is no limitation to the depth of namespaces, up to the [overall K8s limit of 10k namespaces](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md). However, it is _likely_ that:
* You'll run into some other K8s scalability threshold long before you hit 10k namespaces
* HNC itself does struggle as you get into hundreds or thousands of related namespaces.

For example, if you have a long line of namespaces descended from each other (as follows: `parent <- child <- grandchild <- greatgrandchild <- etc`), each namespace will contains some labels and objects that need to be propagated, so you land up with O(n^2) operations. By contrast, if you have a flat namespace structure, each namespace can be updated independently and the load on HNC is only O(n).

In practice, we've found that HNC scales very well to what we consider to be "realistic" testcases. @yiqigao217 , can you please summarize the results of your scalability tests here? Then assign this case back to me and I can add them to the user guide.

/assign @yiqigao217

**Comment by yiqigao217** [comment]
We tested various topologies up to about 500 namespaces for flat and well-balanced hierarchies. The only thing that slowed down was how long it took for HNC to start/restart (about 200s in the worst case) but after that, new policies propagated more-or-less instantly.

/assign @adrianludwin to add it to the user guide.
/unassign @yiqigao217

**Comment by tcnksm** [comment]
Thank you for answering. 

> The only thing that slowed down was how long it took for HNC to start/restart (about 200s in the worst case) but after that

Does this happen when we have around 500 namespaces? Since HNC also handles the admission webhook, if restarting takes a long time, it may affect other kubernetes API operation, I think. 

---

The following are expected numbers of our context.

- The number of namespaces: 250
- The expected nested levels: 3
- The expected number of children: 5-10

I think this is not beyond what you expect and can scale more for a while.

**Comment by adrianludwin** [comment]
Hi @tcnksm , the startup times are roughly linear with the number of namespaces and affected objects. The limitation is actually on the Kubernetes side - we discovered that most GKE clusters can support a maximum of 100 QPS to the apiserver for a sustained period of time, so we [set the HNC limit to half of that](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/config/manager/manager.yaml#L44). We found that if we set this value too high, HNC could destabilize other workloads during startup. My guess is that for 250 namespaces, your startup time will be fairly reasonable, but your best bet is to create an artificial test case and try it out. 

It's also important to note that during HNC startup, your cluster is _not_ down - HNC's webhooks _are_ responsive so they will not block operations on your cluster. The biggest problems you may face are that:

- Some namespaces may temporarily and incorrectly appear to have [error conditions](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#admin-conditions), which will prevent you from _modifying_ the existing hierarchy during this time.
- If you attempt to create a _new_ subnamespace during startup, it may not be fully created until after the startup completes.

Neither of these should typically cause any downtime for your cluster.

Does this all make sense? Thanks!

**Comment by tcnksm** [comment]
> It's also important to note that during HNC startup, your cluster is not down - HNC's webhooks are responsive so they will not block operations on your cluster. The biggest problems you may face are that:

These namespace modification does not happen often compared with other resource modification so I think these problems are fine for us. 

---

We will try and evaluate HNC more on our context in the development environment. Thank you for your answer!

**Comment by adrianludwin** [comment]
Thanks @tcnksm ! I'll leave this issue open as a reminder to go update the docs with this information.
