### ISSUE TITLE
HNC: demo_test.go can't run on KIND cluster

### ISSUE THREAD

**Issue by GinnyJI** [kubernetes-sigs/multi-tenancy#974]
KIND doesn't support Network Policy, so the demo_test.go can't run on KIND

**Comment by GinnyJI** [comment]
Kind doesn't support network policies out of the box: https://github.com/kubernetes-sigs/kind/issues/1006

One possible solution: try to install Calico on Kind (Calico is the networking plugin that supports Network Policies)

**Comment by mugdha-adhav** [comment]
I would like to work on this.

**Comment by adrianludwin** [comment]
@mugdha-adhav - please go ahead! I think what we'd be looking for here is a bash script checked into `/hack` that can set up a KIND cluster with network policies and successfully run all the tests in `/test/e2e`.

**Comment by adrianludwin** [comment]
And thanks @mugdha-adhav for your help!

**Comment by mbtamuli** [comment]
I'd like to work on this issue if you're not able to take a look at it currently @mugdha-adhav

**Comment by adrianludwin** [comment]
Mriyam - please go ahead! I* just* modified the e2e tests so that the
network policy test is skipped if basic network policies don't work. But if
you can figure out a way to make network policies work on KIND, that would
be even better. Are you interested in looking into that?

**Comment by mbtamuli** [comment]
I saw your previous comment and looked into installing calico with kind following [this guide](https://alexbrand.dev/post/creating-a-kind-cluster-with-calico-networking/). I have been able to manually run it. 

Now I need to see if the network policy tests in demo_tests.go are able to run. I'll need to add everything in a script.

**Comment by adrianludwin** [comment]
Putting the script in the hack/ directory (e.g.
`run-on-kind-with-calico.sh`) would be great, then we can integrate it into
our postsubmits when we have them!

**Comment by adrianludwin** [comment]
I think we have sufficient coverage of this now even without netpol on Kind. At least we cleanly skip the test now.

/close
