### ISSUE TITLE
HNC: rename plugin back to kubectl-hnc

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#979]
The HNC kubectl plugin was originally called `kubectl-hnc`, but a few months ago we renamed it to `kubectl-hns`, where HNS stands for "Hierarchical NameSpace." At one point, the term "HNS" was also used for what we now call "subnamespaces," and so the term "HNS" was quite prevalent in HNC documentation and examples. However, those eventually all went away, and the kubectl plugin is now the only remaining instance of this name.

We _are_ hoping to move HNC to its own `github.com/kubernetes-sigs/hierarchical-namespaces` repo in the future, but even then I see "hierarchical namespace" as the name of the feature, not the product, which will continue to be HNC. So I don't see much future for the term "HNS."

As a result, I'd like to change the name of the plugin back to `kubectl-hnc`, since the term "HNC" is far more recognizable. Since kubectl plugins are simply binaries in the user's `PATH`, they can easily rename it to anything they want anyway if this causes anyone problems.

The new name will be used in the following places:
* All HNC documentation
* The list of artifacts in the download page
* The Krew plugin repo (soon)

Concretely, here's what I'm proposing:
* For all supported versions of HNC (0.4.0, 0.5.0 and 0.5.1), _add_ a copy of the `kubectl-hns` binary called `kubectl-hnc`.
* Update all existing documentation to refer to the new plugin name, with a footnote that it used to have a different name
* Starting with 0.6.x, only create `kubectl-hnc`
* The Krew plugin will be called `kubectl-hnc` from the beginning.

**Comment by rjbez17** [comment]
100% agree with the name change.

**Comment by adrianludwin** [comment]
We had some strong objections to this internally at Google - given the lack of consensus, I'm withdrawing this proposal. We can see if it causes more confusion in the future and reconsider then.

**Comment by tcnksm** [comment]
Really agreed on this change. When I tried it for the first time, I typed `kubectl hnc` and took the time to understand that name is different 😄

**Comment by adrianludwin** [comment]
Let's think this when we're getting closer to v1.0.

/close
