### ISSUE TITLE
HNC: Deleting anchors using the short name `subns` takes minutes after deploying API conversion

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#989]
This is set up by deploying v0.5 and applying `config/sample/v1alpha1_anchor.yaml` to have a namespace `a` and a subnamespace `b` of `a`.

After deploying the HEAD (with API conversion), it takes more than 3 minutes for `delete subns b -n a` to work. Before that, it returns:
```
Error from server (NotFound): the server could not find the requested resource (delete subnamespaceanchors.hnc.x-k8s.io b)
```

In the log, I can see the reconcilers having errors:
```
 "Operation cannot be fulfilled on subnamespaceanchors.hnc.x-k8s.io "b": the object has been modified; please apply your changes to the latest version and try again" 
```

Without deploying the conversion, in v0.5, `delete subns b -n a` works almost immediately.

**Comment by yiqigao217** [comment]
/assign @yiqigao217 
/cc @adrianludwin 
Part of #868

**Comment by adrianludwin** [comment]
@yiqigao217 are we still seeing this?

**Comment by yiqigao217** [comment]
Yes, it's still the exact same and it feels even longer (which may be quite random as long as the error and log msg are the same).

**Comment by adrianludwin** [comment]
So how are the conversion tests passing?

**Comment by adrianludwin** [comment]
Discussed offline. The tests use the full name (`subnamespaceanchor.hnc.x-k8s.io`), not the short name (`subns`). It's only the latter that is slow; the former works ~instantly.

I doubt this is a problem with HNC itself; it seems more like a K8s discovery issue. I'm going to take this out of v0.6 for now.

**Comment by adrianludwin** [comment]
Let's at least have a look in v0.7 to see if there's anything we can do, but this might just turn into a bug against K8s (assuming there isn't one already).

**Comment by adrianludwin** [comment]
Haven't had a chance to look at this but I don't think it's a v0.7 issue.

I'll put this in the backlog but we'd appreciate any help we can get on this one.

/help

**Comment by yiqigao217** [comment]
/close

Asked Jordan offline:
> This is similar to this issue: https://github.com/kubernetes/kubernetes/issues/65517
>
> Discovery information (which includes the shortname) is cached locally for O(10 minutes). Requesting an unknown shortname triggers fetching new discovery data (though it does not rescan the newly fetched data to satisfy shortname matching until the next invocation, which is issue 65517). If there is a cached resource/version for the shortname you specify, the client will use that without rediscovering available versions.
>
> Making the old version unavailable leaves clients with cached discovery data pointing to stale endpoints for a few minutes.
