### ISSUE TITLE
HNC: ensure hierarchy doesn't violate required children

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#99]
Once #90 is complete, we should add a validating webhook to ensure that required children are not reassigned to the wrong parents.

/good-first-issue

**Comment by shivi28** [comment]
Hello @adrianludwin. Can I pick up this issue.

**Comment by adrianludwin** [comment]
Hi @shivi28 , I'd actually recommend #130 instead as your very first issue, then maybe come back to this one later?

**Comment by adrianludwin** [comment]
As soon as #156 is merged (which restructures most of the HC validator), this should be relatively easy to implement.

**Comment by shivi28** [comment]
> As soon as #156 is merged (which restructures most of the HC validator), this should be relatively easy to implement.
Now I am

**Comment by adrianludwin** [comment]
/assign @lafh 

Laetitia's working on webhooks anyway so this probably easier for her
